import { NodePgDatabase } from 'drizzle-orm/node-postgres';
import { eq } from 'drizzle-orm';
import { inventoryItems, inventoryConsumptionTracking } from '../schemas';
import * as schema from '../schemas';

export async function seedInventory(db: NodePgDatabase<typeof schema>) {
  console.log('🌱 Seeding inventory items...');

  // Get the first available tenant for seeding
  const existingTenant = await db.query.tenantsTable.findFirst();
  if (!existingTenant) {
    console.log('⚠️ No tenant found. Run users seed first.');
    return;
  }
  const tenantId = existingTenant.id;
  console.log('🏢 Using tenant:', existingTenant.businessName);

  // Check for existing inventory to prevent duplicates
  const existingInventory = await db
    .select()
    .from(inventoryItems)
    .where(eq(inventoryItems.tenantId, tenantId));

  if (existingInventory.length > 0) {
    console.log(`📦 Found ${existingInventory.length} existing inventory items, skipping seed`);
    return;
  }

  const now = new Date();
  const sevenDaysAgo = new Date(now.getTime() - 7 * 24 * 60 * 60 * 1000);

  // Define inventory items without tenantId first
  const inventoryData = [
      // ========== INGREDIENTS ==========

      // Flours
      {
        name: 'All-Purpose Flour',
        category: 'ingredient',
        unit: 'kg',
        currentStock: '150.500',
        minimumStock: '50.000',
        reorderPoint: '75.000',
        reorderQuantity: '100.000',
        costPerUnit: '1.2500',
        supplier: 'King Arthur Flour Co.',
        location: 'Dry Storage Room A',
        lastRestocked: sevenDaysAgo,
        notes: 'Premium unbleached flour for general baking',
      },
      {
        name: 'Bread Flour',
        category: 'ingredient',
        unit: 'kg',
        currentStock: '85.000',
        minimumStock: '40.000',
        reorderPoint: '60.000',
        reorderQuantity: '80.000',
        costPerUnit: '1.4500',
        supplier: 'King Arthur Flour Co.',
        location: 'Dry Storage Room A',
        lastRestocked: sevenDaysAgo,
        notes: 'High protein content for artisan breads',
      },
      {
        name: 'Cake Flour',
        category: 'ingredient',
        unit: 'kg',
        currentStock: '32.000',
        minimumStock: '20.000',
        reorderPoint: '30.000',
        reorderQuantity: '50.000',
        costPerUnit: '1.8500',
        supplier: 'King Arthur Flour Co.',
        location: 'Dry Storage Room A',
        lastRestocked: now,
        notes: 'Fine texture for cakes and pastries',
      },
      {
        name: 'Whole Wheat Flour',
        category: 'ingredient',
        unit: 'kg',
        currentStock: '28.500',
        minimumStock: '15.000',
        reorderPoint: '25.000',
        reorderQuantity: '40.000',
        costPerUnit: '1.6500',
        supplier: 'King Arthur Flour Co.',
        location: 'Dry Storage Room A',
        lastRestocked: sevenDaysAgo,
        notes: 'Stone-ground whole wheat',
      },
      {
        name: 'Rye Flour',
        category: 'ingredient',
        unit: 'kg',
        currentStock: '18.000',
        minimumStock: '10.000',
        reorderPoint: '15.000',
        reorderQuantity: '25.000',
        costPerUnit: '2.2500',
        supplier: 'Organic Mill Co.',
        location: 'Dry Storage Room A',
        lastRestocked: sevenDaysAgo,
        notes: 'Medium rye for specialty breads',
      },

      // Sugars & Sweeteners
      {
        name: 'Granulated Sugar',
        category: 'ingredient',
        unit: 'kg',
        currentStock: '95.000',
        minimumStock: '30.000',
        reorderPoint: '50.000',
        reorderQuantity: '75.000',
        costPerUnit: '0.8500',
        supplier: 'Sweet Supply Co.',
        location: 'Dry Storage Room B',
        lastRestocked: sevenDaysAgo,
        notes: 'Fine granulated white sugar',
      },
      {
        name: 'Brown Sugar',
        category: 'ingredient',
        unit: 'kg',
        currentStock: '42.000',
        minimumStock: '20.000',
        reorderPoint: '30.000',
        reorderQuantity: '50.000',
        costPerUnit: '1.1500',
        supplier: 'Sweet Supply Co.',
        location: 'Dry Storage Room B',
        lastRestocked: now,
        notes: 'Light brown sugar for cookies and cakes',
      },
      {
        name: 'Powdered Sugar',
        category: 'ingredient',
        unit: 'kg',
        currentStock: '25.000',
        minimumStock: '15.000',
        reorderPoint: '20.000',
        reorderQuantity: '30.000',
        costPerUnit: '1.2500',
        supplier: 'Sweet Supply Co.',
        location: 'Dry Storage Room B',
        lastRestocked: sevenDaysAgo,
        notes: 'Confectioners sugar for frosting and dusting',
      },
      {
        name: 'Honey',
        category: 'ingredient',
        unit: 'kg',
        currentStock: '15.500',
        minimumStock: '8.000',
        reorderPoint: '12.000',
        reorderQuantity: '20.000',
        costPerUnit: '8.5000',
        supplier: 'Local Bee Farm',
        location: 'Dry Storage Room B',
        lastRestocked: now,
        notes: 'Raw local honey',
      },

      // Fats & Oils
      {
        name: 'Unsalted Butter',
        category: 'ingredient',
        unit: 'kg',
        currentStock: '68.000',
        minimumStock: '30.000',
        reorderPoint: '45.000',
        reorderQuantity: '60.000',
        costPerUnit: '6.5000',
        supplier: 'Premium Dairy Co.',
        location: 'Walk-in Refrigerator',
        lastRestocked: sevenDaysAgo,
        expirationDate: new Date(now.getTime() + 30 * 24 * 60 * 60 * 1000)
          .toISOString()
          .split('T')[0],
        notes: 'European-style 82% butterfat',
      },
      {
        name: 'Vegetable Oil',
        category: 'ingredient',
        unit: 'l',
        currentStock: '45.000',
        minimumStock: '20.000',
        reorderPoint: '30.000',
        reorderQuantity: '50.000',
        costPerUnit: '4.2500',
        supplier: 'Culinary Oils Inc.',
        location: 'Dry Storage Room B',
        lastRestocked: sevenDaysAgo,
        notes: 'Neutral flavor for baking',
      },
      {
        name: 'Olive Oil',
        category: 'ingredient',
        unit: 'l',
        currentStock: '12.500',
        minimumStock: '8.000',
        reorderPoint: '10.000',
        reorderQuantity: '15.000',
        costPerUnit: '12.5000',
        supplier: 'Mediterranean Imports',
        location: 'Dry Storage Room B',
        lastRestocked: now,
        notes: 'Extra virgin for focaccia and specialty breads',
      },

      // Dairy & Eggs
      {
        name: 'Whole Milk',
        category: 'ingredient',
        unit: 'l',
        currentStock: '85.000',
        minimumStock: '40.000',
        reorderPoint: '60.000',
        reorderQuantity: '80.000',
        costPerUnit: '1.2500',
        supplier: 'Premium Dairy Co.',
        location: 'Walk-in Refrigerator',
        lastRestocked: now,
        expirationDate: new Date(now.getTime() + 7 * 24 * 60 * 60 * 1000)
          .toISOString()
          .split('T')[0],
        notes: 'Fresh whole milk 3.5% fat',
      },
      {
        name: 'Heavy Cream',
        category: 'ingredient',
        unit: 'l',
        currentStock: '28.000',
        minimumStock: '15.000',
        reorderPoint: '20.000',
        reorderQuantity: '30.000',
        costPerUnit: '4.5000',
        supplier: 'Premium Dairy Co.',
        location: 'Walk-in Refrigerator',
        lastRestocked: sevenDaysAgo,
        expirationDate: new Date(now.getTime() + 14 * 24 * 60 * 60 * 1000)
          .toISOString()
          .split('T')[0],
        notes: '36% butterfat for whipping',
      },
      {
        name: 'Large Eggs',
        category: 'ingredient',
        unit: 'dozen',
        currentStock: '48.000',
        minimumStock: '20.000',
        reorderPoint: '30.000',
        reorderQuantity: '50.000',
        costPerUnit: '4.2500',
        supplier: 'Free Range Farms',
        location: 'Walk-in Refrigerator',
        lastRestocked: sevenDaysAgo,
        expirationDate: new Date(now.getTime() + 21 * 24 * 60 * 60 * 1000)
          .toISOString()
          .split('T')[0],
        notes: 'Grade A large eggs',
      },
      {
        name: 'Cream Cheese',
        category: 'ingredient',
        unit: 'kg',
        currentStock: '15.000',
        minimumStock: '8.000',
        reorderPoint: '12.000',
        reorderQuantity: '20.000',
        costPerUnit: '7.5000',
        supplier: 'Premium Dairy Co.',
        location: 'Walk-in Refrigerator',
        lastRestocked: now,
        expirationDate: new Date(now.getTime() + 30 * 24 * 60 * 60 * 1000)
          .toISOString()
          .split('T')[0],
        notes: 'Full-fat cream cheese for frostings',
      },

      // Leavening Agents
      {
        name: 'Active Dry Yeast',
        category: 'ingredient',
        unit: 'kg',
        currentStock: '8.500',
        minimumStock: '3.000',
        reorderPoint: '5.000',
        reorderQuantity: '10.000',
        costPerUnit: '18.5000',
        supplier: 'Baking Essentials Ltd.',
        location: 'Walk-in Refrigerator',
        lastRestocked: sevenDaysAgo,
        notes: 'Premium instant yeast for bread production',
      },
      {
        name: 'Baking Powder',
        category: 'ingredient',
        unit: 'kg',
        currentStock: '12.000',
        minimumStock: '5.000',
        reorderPoint: '8.000',
        reorderQuantity: '15.000',
        costPerUnit: '8.2500',
        supplier: 'Baking Essentials Ltd.',
        location: 'Dry Storage Room A',
        lastRestocked: now,
        notes: 'Double-acting baking powder',
      },
      {
        name: 'Baking Soda',
        category: 'ingredient',
        unit: 'kg',
        currentStock: '8.500',
        minimumStock: '3.000',
        reorderPoint: '5.000',
        reorderQuantity: '10.000',
        costPerUnit: '3.5000',
        supplier: 'Baking Essentials Ltd.',
        location: 'Dry Storage Room A',
        lastRestocked: sevenDaysAgo,
        notes: 'Sodium bicarbonate for quick breads',
      },

      // Chocolate & Cocoa
      {
        name: 'Dark Chocolate Chips',
        category: 'ingredient',
        unit: 'kg',
        currentStock: '22.500',
        minimumStock: '10.000',
        reorderPoint: '15.000',
        reorderQuantity: '25.000',
        costPerUnit: '12.5000',
        supplier: 'Belgian Chocolate Imports',
        location: 'Dry Storage Room C',
        lastRestocked: sevenDaysAgo,
        notes: '70% cacao semi-sweet chips',
      },
      {
        name: 'Cocoa Powder',
        category: 'ingredient',
        unit: 'kg',
        currentStock: '18.000',
        minimumStock: '8.000',
        reorderPoint: '12.000',
        reorderQuantity: '20.000',
        costPerUnit: '15.5000',
        supplier: 'Belgian Chocolate Imports',
        location: 'Dry Storage Room C',
        lastRestocked: now,
        notes: 'Dutch-processed cocoa powder',
      },
      {
        name: 'White Chocolate',
        category: 'ingredient',
        unit: 'kg',
        currentStock: '9.500',
        minimumStock: '5.000',
        reorderPoint: '8.000',
        reorderQuantity: '15.000',
        costPerUnit: '18.5000',
        supplier: 'Belgian Chocolate Imports',
        location: 'Dry Storage Room C',
        lastRestocked: sevenDaysAgo,
        notes: 'Premium white chocolate for decorating',
      },

      // Nuts & Seeds
      {
        name: 'Almonds (Sliced)',
        category: 'ingredient',
        unit: 'kg',
        currentStock: '12.000',
        minimumStock: '5.000',
        reorderPoint: '8.000',
        reorderQuantity: '15.000',
        costPerUnit: '14.5000',
        supplier: 'Nuts & More Inc.',
        location: 'Dry Storage Room C',
        lastRestocked: sevenDaysAgo,
        notes: 'Blanched sliced almonds',
      },
      {
        name: 'Walnuts (Chopped)',
        category: 'ingredient',
        unit: 'kg',
        currentStock: '8.500',
        minimumStock: '4.000',
        reorderPoint: '6.000',
        reorderQuantity: '10.000',
        costPerUnit: '16.5000',
        supplier: 'Nuts & More Inc.',
        location: 'Dry Storage Room C',
        lastRestocked: now,
        notes: 'Chopped walnuts for breads and brownies',
      },
      {
        name: 'Sesame Seeds',
        category: 'ingredient',
        unit: 'kg',
        currentStock: '5.500',
        minimumStock: '2.000',
        reorderPoint: '3.500',
        reorderQuantity: '8.000',
        costPerUnit: '8.5000',
        supplier: 'Spice & Seed Co.',
        location: 'Dry Storage Room C',
        lastRestocked: sevenDaysAgo,
        notes: 'White sesame seeds for bread topping',
      },

      // Flavorings & Extracts
      {
        name: 'Vanilla Extract',
        category: 'ingredient',
        unit: 'l',
        currentStock: '3.500',
        minimumStock: '1.500',
        reorderPoint: '2.500',
        reorderQuantity: '5.000',
        costPerUnit: '85.5000',
        supplier: 'Flavor Essence Co.',
        location: 'Dry Storage Room B',
        lastRestocked: now,
        notes: 'Pure Madagascar vanilla extract',
      },
      {
        name: 'Almond Extract',
        category: 'ingredient',
        unit: 'ml',
        currentStock: '850.000',
        minimumStock: '500.000',
        reorderPoint: '750.000',
        reorderQuantity: '1000.000',
        costPerUnit: '0.0450',
        supplier: 'Flavor Essence Co.',
        location: 'Dry Storage Room B',
        lastRestocked: sevenDaysAgo,
        notes: 'Pure almond extract',
      },
      {
        name: 'Cinnamon (Ground)',
        category: 'ingredient',
        unit: 'kg',
        currentStock: '4.500',
        minimumStock: '2.000',
        reorderPoint: '3.000',
        reorderQuantity: '5.000',
        costPerUnit: '18.5000',
        supplier: 'Spice & Seed Co.',
        location: 'Dry Storage Room B',
        lastRestocked: sevenDaysAgo,
        notes: 'Ceylon cinnamon',
      },
      {
        name: 'Sea Salt',
        category: 'ingredient',
        unit: 'kg',
        currentStock: '15.000',
        minimumStock: '8.000',
        reorderPoint: '10.000',
        reorderQuantity: '20.000',
        costPerUnit: '4.5000',
        supplier: 'Spice & Seed Co.',
        location: 'Dry Storage Room B',
        lastRestocked: now,
        notes: 'Fine sea salt for baking',
      },

      // Fruits & Fillings
      {
        name: 'Frozen Blueberries',
        category: 'ingredient',
        unit: 'kg',
        currentStock: '25.000',
        minimumStock: '10.000',
        reorderPoint: '15.000',
        reorderQuantity: '30.000',
        costPerUnit: '8.5000',
        supplier: 'Berry Fresh Co.',
        location: 'Walk-in Freezer',
        lastRestocked: sevenDaysAgo,
        notes: 'IQF wild blueberries',
      },
      {
        name: 'Raspberry Jam',
        category: 'ingredient',
        unit: 'kg',
        currentStock: '12.500',
        minimumStock: '6.000',
        reorderPoint: '9.000',
        reorderQuantity: '15.000',
        costPerUnit: '12.5000',
        supplier: 'Preserve Makers Inc.',
        location: 'Dry Storage Room C',
        lastRestocked: now,
        notes: 'Premium seedless raspberry preserves',
      },
      {
        name: 'Lemon Juice',
        category: 'ingredient',
        unit: 'l',
        currentStock: '8.500',
        minimumStock: '4.000',
        reorderPoint: '6.000',
        reorderQuantity: '10.000',
        costPerUnit: '6.5000',
        supplier: 'Citrus Fresh Co.',
        location: 'Walk-in Refrigerator',
        lastRestocked: sevenDaysAgo,
        notes: 'Fresh-squeezed lemon juice',
      },

      // ========== PACKAGING ==========

      {
        name: 'Bakery Boxes (9 inch)',
        category: 'packaging',
        unit: 'unit',
        currentStock: '450.000',
        minimumStock: '200.000',
        reorderPoint: '300.000',
        reorderQuantity: '500.000',
        costPerUnit: '0.4500',
        supplier: 'Package Pro Inc.',
        location: 'Packaging Storage',
        lastRestocked: sevenDaysAgo,
        notes: 'White bakery boxes with window',
      },
      {
        name: 'Bread Bags (Large)',
        category: 'packaging',
        unit: 'unit',
        currentStock: '850.000',
        minimumStock: '400.000',
        reorderPoint: '600.000',
        reorderQuantity: '1000.000',
        costPerUnit: '0.0850',
        supplier: 'Package Pro Inc.',
        location: 'Packaging Storage',
        lastRestocked: now,
        notes: 'Clear plastic bread bags with twist ties',
      },
      {
        name: 'Cupcake Liners',
        category: 'packaging',
        unit: 'unit',
        currentStock: '2500.000',
        minimumStock: '1000.000',
        reorderPoint: '1500.000',
        reorderQuantity: '3000.000',
        costPerUnit: '0.0250',
        supplier: 'Baking Supplies Co.',
        location: 'Packaging Storage',
        lastRestocked: sevenDaysAgo,
        notes: 'Standard white paper cupcake liners',
      },
      {
        name: 'Parchment Paper Sheets',
        category: 'packaging',
        unit: 'unit',
        currentStock: '1200.000',
        minimumStock: '500.000',
        reorderPoint: '800.000',
        reorderQuantity: '1500.000',
        costPerUnit: '0.1250',
        supplier: 'Baking Supplies Co.',
        location: 'Packaging Storage',
        lastRestocked: now,
        notes: 'Pre-cut parchment sheets for sheet pans',
      },
      {
        name: 'Plastic Food Wrap',
        category: 'packaging',
        unit: 'unit',
        currentStock: '15.000',
        minimumStock: '8.000',
        reorderPoint: '12.000',
        reorderQuantity: '20.000',
        costPerUnit: '12.5000',
        supplier: 'Package Pro Inc.',
        location: 'Packaging Storage',
        lastRestocked: sevenDaysAgo,
        notes: 'Commercial-grade cling wrap rolls',
      },
      {
        name: 'Aluminum Foil Rolls',
        category: 'packaging',
        unit: 'unit',
        currentStock: '8.000',
        minimumStock: '5.000',
        reorderPoint: '6.000',
        reorderQuantity: '10.000',
        costPerUnit: '18.5000',
        supplier: 'Package Pro Inc.',
        location: 'Packaging Storage',
        lastRestocked: now,
        notes: 'Heavy-duty aluminum foil',
      },
      {
        name: 'Paper Napkins',
        category: 'packaging',
        unit: 'unit',
        currentStock: '3500.000',
        minimumStock: '1500.000',
        reorderPoint: '2500.000',
        reorderQuantity: '5000.000',
        costPerUnit: '0.0150',
        supplier: 'Package Pro Inc.',
        location: 'Packaging Storage',
        lastRestocked: sevenDaysAgo,
        notes: 'White cocktail napkins with logo',
      },
      {
        name: 'Cake Boards (10 inch)',
        category: 'packaging',
        unit: 'unit',
        currentStock: '180.000',
        minimumStock: '75.000',
        reorderPoint: '120.000',
        reorderQuantity: '200.000',
        costPerUnit: '0.8500',
        supplier: 'Package Pro Inc.',
        location: 'Packaging Storage',
        lastRestocked: now,
        notes: 'Gold foil cake boards',
      },

      // ========== SUPPLIES ==========

      {
        name: 'Disposable Gloves (Medium)',
        category: 'supplies',
        unit: 'unit',
        currentStock: '450.000',
        minimumStock: '200.000',
        reorderPoint: '300.000',
        reorderQuantity: '500.000',
        costPerUnit: '0.1250',
        supplier: 'Safety First Inc.',
        location: 'Supply Closet',
        lastRestocked: sevenDaysAgo,
        notes: 'Nitrile disposable gloves, powder-free',
      },
      {
        name: 'Hair Nets',
        category: 'supplies',
        unit: 'unit',
        currentStock: '280.000',
        minimumStock: '150.000',
        reorderPoint: '200.000',
        reorderQuantity: '300.000',
        costPerUnit: '0.0850',
        supplier: 'Safety First Inc.',
        location: 'Supply Closet',
        lastRestocked: now,
        notes: 'White nylon hair nets',
      },
      {
        name: 'Aprons',
        category: 'supplies',
        unit: 'unit',
        currentStock: '25.000',
        minimumStock: '15.000',
        reorderPoint: '20.000',
        reorderQuantity: '30.000',
        costPerUnit: '8.5000',
        supplier: 'Safety First Inc.',
        location: 'Supply Closet',
        lastRestocked: sevenDaysAgo,
        notes: 'White cotton aprons',
      },
      {
        name: 'Sanitizer Solution',
        category: 'supplies',
        unit: 'l',
        currentStock: '18.500',
        minimumStock: '10.000',
        reorderPoint: '15.000',
        reorderQuantity: '25.000',
        costPerUnit: '6.5000',
        supplier: 'Clean Pro Supplies',
        location: 'Supply Closet',
        lastRestocked: now,
        notes: 'Food-safe sanitizing solution',
      },
      {
        name: 'Cleaning Cloths',
        category: 'supplies',
        unit: 'unit',
        currentStock: '150.000',
        minimumStock: '75.000',
        reorderPoint: '100.000',
        reorderQuantity: '200.000',
        costPerUnit: '1.2500',
        supplier: 'Clean Pro Supplies',
        location: 'Supply Closet',
        lastRestocked: sevenDaysAgo,
        notes: 'Microfiber cleaning cloths',
      },
      {
        name: 'Oven Thermometer',
        category: 'supplies',
        unit: 'unit',
        currentStock: '4.000',
        minimumStock: '2.000',
        reorderPoint: '3.000',
        reorderQuantity: '5.000',
        costPerUnit: '18.5000',
        supplier: 'Kitchen Equipment Co.',
        location: 'Supply Closet',
        lastRestocked: now,
        notes: 'Digital oven thermometers',
      },
      {
        name: 'Pastry Brushes',
        category: 'supplies',
        unit: 'unit',
        currentStock: '12.000',
        minimumStock: '6.000',
        reorderPoint: '9.000',
        reorderQuantity: '15.000',
        costPerUnit: '4.5000',
        supplier: 'Baking Tools Inc.',
        location: 'Supply Closet',
        lastRestocked: sevenDaysAgo,
        notes: 'Silicone pastry brushes',
      },
      {
        name: 'Piping Bags (Disposable)',
        category: 'supplies',
        unit: 'unit',
        currentStock: '320.000',
        minimumStock: '150.000',
        reorderPoint: '250.000',
        reorderQuantity: '400.000',
        costPerUnit: '0.2500',
        supplier: 'Baking Tools Inc.',
        location: 'Supply Closet',
        lastRestocked: now,
        notes: '16-inch disposable piping bags',
      },
  ];

  // Add tenantId to all items and insert with proper typing
  const items = await db
    .insert(inventoryItems)
    .values(inventoryData.map(item => ({
      ...item,
      tenantId,
      category: item.category as 'ingredient' | 'packaging' | 'supplies',
      unit: item.unit as 'kg' | 'g' | 'l' | 'ml' | 'unit' | 'dozen',
    })))
    .onConflictDoNothing()
    .returning();

  console.log(`✅ Created ${items.length} inventory items`);

  // Create consumption tracking for some items
  if (items.length > 0) {
    const trackingData = [
      // High consumption items
      {
        inventoryItemId: items[0]!.id, // All-Purpose Flour
        avgDailyConsumption: '12.500',
        calculationPeriodDays: 7,
        lastCalculatedAt: now,
        calculationMethod: 'historical_orders',
        sampleSize: 42,
      },
      {
        inventoryItemId: items[1]!.id, // Bread Flour
        avgDailyConsumption: '8.750',
        calculationPeriodDays: 7,
        lastCalculatedAt: now,
        calculationMethod: 'historical_orders',
        sampleSize: 38,
      },
      {
        inventoryItemId: items[5]!.id, // Granulated Sugar
        avgDailyConsumption: '6.250',
        calculationPeriodDays: 7,
        lastCalculatedAt: now,
        calculationMethod: 'historical_orders',
        sampleSize: 35,
      },
      {
        inventoryItemId: items[9]!.id, // Unsalted Butter
        avgDailyConsumption: '5.500',
        calculationPeriodDays: 7,
        lastCalculatedAt: now,
        calculationMethod: 'historical_orders',
        sampleSize: 40,
      },
      {
        inventoryItemId: items[14]!.id, // Large Eggs
        avgDailyConsumption: '4.200',
        calculationPeriodDays: 7,
        lastCalculatedAt: now,
        calculationMethod: 'historical_orders',
        sampleSize: 28,
      },
      // Medium consumption items
      {
        inventoryItemId: items[2]!.id, // Cake Flour
        avgDailyConsumption: '3.800',
        calculationPeriodDays: 7,
        lastCalculatedAt: now,
        calculationMethod: 'historical_orders',
        sampleSize: 22,
      },
      {
        inventoryItemId: items[12]!.id, // Whole Milk
        avgDailyConsumption: '8.500',
        calculationPeriodDays: 7,
        lastCalculatedAt: now,
        calculationMethod: 'historical_orders',
        sampleSize: 30,
      },
      {
        inventoryItemId: items[19]!.id, // Dark Chocolate Chips
        avgDailyConsumption: '2.100',
        calculationPeriodDays: 7,
        lastCalculatedAt: now,
        calculationMethod: 'historical_orders',
        sampleSize: 18,
      },
      // Low consumption specialty items
      {
        inventoryItemId: items[4]!.id, // Rye Flour
        avgDailyConsumption: '1.200',
        calculationPeriodDays: 7,
        lastCalculatedAt: now,
        calculationMethod: 'historical_orders',
        sampleSize: 8,
      },
      {
        inventoryItemId: items[25]!.id, // Vanilla Extract
        avgDailyConsumption: '0.350',
        calculationPeriodDays: 7,
        lastCalculatedAt: now,
        calculationMethod: 'historical_orders',
        sampleSize: 25,
      },
      // Items with custom thresholds
      {
        inventoryItemId: items[16]!.id, // Active Dry Yeast
        avgDailyConsumption: '0.850',
        calculationPeriodDays: 7,
        lastCalculatedAt: now,
        calculationMethod: 'manual',
        customReorderThreshold: '5.000',
        customLeadTimeDays: 7,
        sampleSize: 15,
      },
      {
        inventoryItemId: items[29]!.id, // Frozen Blueberries
        avgDailyConsumption: '2.500',
        calculationPeriodDays: 7,
        lastCalculatedAt: now,
        calculationMethod: 'historical_orders',
        customReorderThreshold: '18.000',
        customLeadTimeDays: 5,
        sampleSize: 12,
      },
    ];

    await db
      .insert(inventoryConsumptionTracking)
      .values(trackingData)
      .onConflictDoNothing();

    console.log(
      `✅ Created ${trackingData.length} consumption tracking records`,
    );
  }

  console.log('✅ Inventory seeded successfully!');
  console.log(`   Total items: ${items.length}`);
  console.log('   - Ingredients: 31');
  console.log('   - Packaging: 8');
  console.log('   - Supplies: 8');
}
