import { NodePgDatabase } from 'drizzle-orm/node-postgres';
import { products } from '../schemas/products.schema';
import * as schema from '../schemas';

export async function seedProducts(db: NodePgDatabase<typeof schema>) {
  console.log('🌱 Seeding products...');

  const sampleProducts = [
    // Breads
    {
      name: 'Sourdough Bread',
      description:
        'Artisan sourdough with a crispy crust and tangy flavor. Made with natural starter.',
      category: 'bread' as const,
      status: 'active' as const,
      basePrice: '5.99',
      costOfGoods: '2.50',
      margin: '58.26',
      estimatedPrepTime: 720, // 12 hours
      allergens: ['gluten'],
      tags: ['artisan', 'popular', 'signature'],
      storageInstructions: 'Store in a paper bag at room temperature',
      shelfLife: 72, // 3 days
      minimumOrderQuantity: 1,
      customizable: false,
      popularityScore: 50,
    },
    {
      name: 'Whole Wheat Baguette',
      description: 'Classic French baguette made with 100% whole wheat flour',
      category: 'bread' as const,
      status: 'active' as const,
      basePrice: '4.50',
      costOfGoods: '1.80',
      margin: '60.00',
      estimatedPrepTime: 180,
      allergens: ['gluten'],
      tags: ['french', 'healthy', 'whole grain'],
      storageInstructions: 'Best consumed within 24 hours',
      shelfLife: 24,
      minimumOrderQuantity: 1,
      customizable: false,
      popularityScore: 35,
    },
    {
      name: 'Ciabatta',
      description: 'Italian white bread with a soft interior and crispy crust',
      category: 'bread' as const,
      status: 'active' as const,
      basePrice: '5.25',
      costOfGoods: '2.00',
      margin: '61.90',
      estimatedPrepTime: 240,
      allergens: ['gluten'],
      tags: ['italian', 'artisan'],
      storageInstructions: 'Store in a cool, dry place',
      shelfLife: 48,
      minimumOrderQuantity: 1,
      customizable: false,
      popularityScore: 28,
    },

    // Pastries
    {
      name: 'Butter Croissant',
      description: 'Flaky, buttery French croissant with 27 layers',
      category: 'pastry' as const,
      status: 'active' as const,
      basePrice: '3.50',
      costOfGoods: '1.20',
      margin: '65.71',
      estimatedPrepTime: 90,
      allergens: ['gluten', 'dairy', 'eggs'],
      tags: ['french', 'breakfast', 'popular'],
      storageInstructions: 'Best fresh, can be frozen',
      shelfLife: 24,
      minimumOrderQuantity: 1,
      customizable: false,
      popularityScore: 75,
    },
    {
      name: 'Almond Croissant',
      description: 'Croissant filled with almond cream and topped with sliced almonds',
      category: 'pastry' as const,
      status: 'active' as const,
      basePrice: '4.75',
      costOfGoods: '1.80',
      margin: '62.11',
      estimatedPrepTime: 100,
      allergens: ['gluten', 'dairy', 'eggs', 'nuts'],
      tags: ['french', 'premium', 'almonds'],
      storageInstructions: 'Refrigerate if not consumed same day',
      shelfLife: 36,
      minimumOrderQuantity: 1,
      customizable: false,
      popularityScore: 60,
    },
    {
      name: 'Danish Pastry',
      description: 'Sweet pastry with various fruit or cream fillings',
      category: 'pastry' as const,
      status: 'active' as const,
      basePrice: '4.25',
      costOfGoods: '1.50',
      margin: '64.71',
      estimatedPrepTime: 85,
      allergens: ['gluten', 'dairy', 'eggs'],
      tags: ['sweet', 'fruit', 'breakfast'],
      storageInstructions: 'Refrigerate after 4 hours',
      shelfLife: 36,
      minimumOrderQuantity: 1,
      customizable: true,
      customizationOptions: [
        {
          name: 'Filling',
          type: 'select' as const,
          options: ['Cherry', 'Apple', 'Cream Cheese', 'Blueberry'],
          required: true,
        },
      ],
      popularityScore: 42,
    },

    // Cakes
    {
      name: 'Chocolate Layer Cake',
      description: 'Rich chocolate cake with chocolate buttercream frosting',
      category: 'cake' as const,
      status: 'active' as const,
      basePrice: '45.00',
      costOfGoods: '18.00',
      margin: '60.00',
      estimatedPrepTime: 180,
      allergens: ['gluten', 'dairy', 'eggs', 'soy'],
      tags: ['celebration', 'chocolate', 'signature'],
      nutritionalInfo: {
        calories: 450,
        fat: 24,
        carbs: 54,
        protein: 6,
        sugar: 36,
      },
      storageInstructions: 'Must be refrigerated',
      shelfLife: 72,
      minimumOrderQuantity: 1,
      customizable: true,
      customizationOptions: [
        {
          name: 'Size',
          type: 'select' as const,
          options: ['6 inch', '8 inch', '10 inch'],
          priceAdjustment: 0,
          required: true,
        },
        {
          name: 'Message',
          type: 'text' as const,
          required: false,
        },
      ],
      popularityScore: 85,
    },
    {
      name: 'Vanilla Birthday Cake',
      description: 'Classic vanilla cake with vanilla buttercream',
      category: 'cake' as const,
      status: 'active' as const,
      basePrice: '42.00',
      costOfGoods: '16.00',
      margin: '61.90',
      estimatedPrepTime: 165,
      allergens: ['gluten', 'dairy', 'eggs'],
      tags: ['celebration', 'birthday', 'vanilla'],
      storageInstructions: 'Must be refrigerated',
      shelfLife: 72,
      minimumOrderQuantity: 1,
      customizable: true,
      customizationOptions: [
        {
          name: 'Size',
          type: 'select' as const,
          options: ['6 inch', '8 inch', '10 inch', '12 inch'],
          required: true,
        },
        {
          name: 'Frosting Color',
          type: 'select' as const,
          options: ['White', 'Pink', 'Blue', 'Yellow', 'Purple'],
          required: false,
        },
        {
          name: 'Message',
          type: 'text' as const,
          required: false,
        },
      ],
      popularityScore: 90,
    },
    {
      name: 'Red Velvet Cake',
      description: 'Southern-style red velvet with cream cheese frosting',
      category: 'cake' as const,
      status: 'active' as const,
      basePrice: '48.00',
      costOfGoods: '20.00',
      margin: '58.33',
      estimatedPrepTime: 170,
      allergens: ['gluten', 'dairy', 'eggs'],
      tags: ['celebration', 'premium', 'signature'],
      storageInstructions: 'Must be refrigerated',
      shelfLife: 72,
      minimumOrderQuantity: 1,
      customizable: true,
      customizationOptions: [
        {
          name: 'Size',
          type: 'select' as const,
          options: ['8 inch', '10 inch'],
          required: true,
        },
        {
          name: 'Message',
          type: 'text' as const,
          required: false,
        },
      ],
      popularityScore: 70,
    },

    // Cookies
    {
      name: 'Chocolate Chip Cookies',
      description: 'Classic cookies loaded with chocolate chips',
      category: 'cookie' as const,
      status: 'active' as const,
      basePrice: '12.00',
      costOfGoods: '4.50',
      margin: '62.50',
      estimatedPrepTime: 30,
      allergens: ['gluten', 'dairy', 'eggs', 'soy'],
      tags: ['classic', 'popular', 'dozen'],
      nutritionalInfo: {
        calories: 180,
        fat: 9,
        carbs: 24,
        protein: 2,
        sugar: 14,
      },
      storageInstructions: 'Store in airtight container',
      shelfLife: 168, // 7 days
      minimumOrderQuantity: 12,
      customizable: false,
      popularityScore: 95,
    },
    {
      name: 'Oatmeal Raisin Cookies',
      description: 'Chewy oatmeal cookies with plump raisins',
      category: 'cookie' as const,
      status: 'active' as const,
      basePrice: '11.00',
      costOfGoods: '4.00',
      margin: '63.64',
      estimatedPrepTime: 28,
      allergens: ['gluten', 'dairy', 'eggs'],
      tags: ['classic', 'healthy', 'dozen'],
      storageInstructions: 'Store in airtight container',
      shelfLife: 168,
      minimumOrderQuantity: 12,
      customizable: false,
      popularityScore: 55,
    },
    {
      name: 'Sugar Cookies',
      description: 'Soft sugar cookies with decorative icing',
      category: 'cookie' as const,
      status: 'active' as const,
      basePrice: '15.00',
      costOfGoods: '5.50',
      margin: '63.33',
      estimatedPrepTime: 45,
      allergens: ['gluten', 'dairy', 'eggs'],
      tags: ['celebration', 'decorated', 'dozen'],
      storageInstructions: 'Store in airtight container',
      shelfLife: 120,
      minimumOrderQuantity: 12,
      customizable: true,
      customizationOptions: [
        {
          name: 'Design',
          type: 'select' as const,
          options: ['Birthday', 'Holiday', 'Wedding', 'Baby Shower', 'Custom'],
          priceAdjustment: 5,
          required: true,
        },
      ],
      popularityScore: 65,
    },

    // Sandwiches
    {
      name: 'Turkey & Swiss Sandwich',
      description: 'Sliced turkey, Swiss cheese, lettuce, tomato on fresh baguette',
      category: 'sandwich' as const,
      status: 'active' as const,
      basePrice: '8.50',
      costOfGoods: '3.50',
      margin: '58.82',
      estimatedPrepTime: 10,
      allergens: ['gluten', 'dairy'],
      tags: ['lunch', 'fresh', 'popular'],
      storageInstructions: 'Refrigerate immediately',
      shelfLife: 12,
      minimumOrderQuantity: 1,
      customizable: true,
      customizationOptions: [
        {
          name: 'Bread',
          type: 'select' as const,
          options: ['Baguette', 'Whole Wheat', 'Ciabatta', 'Sourdough'],
          required: true,
        },
        {
          name: 'Add-ons',
          type: 'checkbox' as const,
          options: ['Avocado', 'Bacon', 'Extra Cheese'],
          priceAdjustment: 1.5,
          required: false,
        },
      ],
      popularityScore: 48,
    },
    {
      name: 'Caprese Sandwich',
      description: 'Fresh mozzarella, tomatoes, basil, balsamic on ciabatta',
      category: 'sandwich' as const,
      status: 'active' as const,
      basePrice: '9.25',
      costOfGoods: '3.80',
      margin: '58.92',
      estimatedPrepTime: 8,
      allergens: ['gluten', 'dairy'],
      tags: ['vegetarian', 'fresh', 'italian'],
      storageInstructions: 'Best consumed fresh, refrigerate if needed',
      shelfLife: 8,
      minimumOrderQuantity: 1,
      customizable: false,
      popularityScore: 38,
    },

    // Beverages
    {
      name: 'Fresh Brewed Coffee',
      description: 'House blend coffee, hot or iced',
      category: 'beverage' as const,
      status: 'active' as const,
      basePrice: '3.50',
      costOfGoods: '0.80',
      margin: '77.14',
      estimatedPrepTime: 3,
      allergens: [],
      tags: ['coffee', 'hot', 'iced'],
      storageInstructions: 'Serve immediately',
      shelfLife: 2,
      minimumOrderQuantity: 1,
      customizable: true,
      customizationOptions: [
        {
          name: 'Size',
          type: 'select' as const,
          options: ['Small', 'Medium', 'Large'],
          priceAdjustment: 0.75,
          required: true,
        },
        {
          name: 'Temperature',
          type: 'select' as const,
          options: ['Hot', 'Iced'],
          required: true,
        },
      ],
      popularityScore: 100,
    },
    {
      name: 'Specialty Latte',
      description: 'Espresso with steamed milk and flavor options',
      category: 'beverage' as const,
      status: 'active' as const,
      basePrice: '5.25',
      costOfGoods: '1.50',
      margin: '71.43',
      estimatedPrepTime: 5,
      allergens: ['dairy'],
      tags: ['coffee', 'espresso', 'specialty'],
      storageInstructions: 'Serve immediately',
      shelfLife: 1,
      minimumOrderQuantity: 1,
      customizable: true,
      customizationOptions: [
        {
          name: 'Flavor',
          type: 'select' as const,
          options: ['Vanilla', 'Caramel', 'Hazelnut', 'Mocha', 'None'],
          priceAdjustment: 0.5,
          required: true,
        },
        {
          name: 'Milk',
          type: 'select' as const,
          options: ['Whole', 'Skim', 'Oat', 'Almond', 'Soy'],
          priceAdjustment: 0.5,
          required: true,
        },
      ],
      popularityScore: 82,
    },

    // More Pastries
    {
      name: 'Pain au Chocolat',
      description: 'Chocolate croissant with dark chocolate batons',
      category: 'pastry' as const,
      status: 'active' as const,
      basePrice: '3.75',
      costOfGoods: '1.35',
      margin: '64.00',
      estimatedPrepTime: 420,
      allergens: ['gluten', 'dairy', 'eggs', 'soy'],
      tags: ['french', 'chocolate', 'premium'],
      storageInstructions: 'Best fresh, can be frozen',
      shelfLife: 24,
      minimumOrderQuantity: 1,
      customizable: false,
      popularityScore: 68,
    },
    {
      name: 'Blueberry Muffin',
      description: 'Fresh blueberry muffins with streusel topping',
      category: 'pastry' as const,
      status: 'active' as const,
      basePrice: '3.25',
      costOfGoods: '1.10',
      margin: '66.15',
      estimatedPrepTime: 42,
      allergens: ['gluten', 'dairy', 'eggs'],
      tags: ['breakfast', 'fruit', 'popular'],
      storageInstructions: 'Store at room temperature',
      shelfLife: 48,
      minimumOrderQuantity: 1,
      customizable: false,
      popularityScore: 72,
    },
    {
      name: 'Cinnamon Roll',
      description: 'Soft cinnamon rolls with cream cheese frosting',
      category: 'pastry' as const,
      status: 'active' as const,
      basePrice: '4.50',
      costOfGoods: '1.50',
      margin: '66.67',
      estimatedPrepTime: 205,
      allergens: ['gluten', 'dairy', 'eggs'],
      tags: ['sweet', 'breakfast', 'signature'],
      storageInstructions: 'Store covered at room temperature',
      shelfLife: 36,
      minimumOrderQuantity: 1,
      customizable: false,
      popularityScore: 85,
    },
    {
      name: 'Scone - Mixed Berry',
      description: 'Traditional English scone with mixed berries',
      category: 'pastry' as const,
      status: 'active' as const,
      basePrice: '3.50',
      costOfGoods: '1.20',
      margin: '65.71',
      estimatedPrepTime: 35,
      allergens: ['gluten', 'dairy', 'eggs'],
      tags: ['british', 'breakfast', 'fruit'],
      storageInstructions: 'Best consumed same day',
      shelfLife: 24,
      minimumOrderQuantity: 1,
      customizable: false,
      popularityScore: 45,
    },

    // More Breads
    {
      name: 'Focaccia',
      description: 'Italian flatbread with rosemary and sea salt',
      category: 'bread' as const,
      status: 'active' as const,
      basePrice: '9.50',
      costOfGoods: '3.20',
      margin: '66.32',
      estimatedPrepTime: 175,
      allergens: ['gluten'],
      tags: ['italian', 'savory', 'artisan'],
      storageInstructions: 'Store in paper bag',
      shelfLife: 48,
      minimumOrderQuantity: 1,
      customizable: false,
      popularityScore: 52,
    },
    {
      name: 'Banana Bread',
      description: 'Moist banana bread with optional walnuts',
      category: 'bread' as const,
      status: 'active' as const,
      basePrice: '8.50',
      costOfGoods: '2.80',
      margin: '67.06',
      estimatedPrepTime: 75,
      allergens: ['gluten', 'dairy', 'eggs'],
      tags: ['quick bread', 'comfort', 'banana'],
      storageInstructions: 'Store wrapped at room temperature',
      shelfLife: 96,
      minimumOrderQuantity: 1,
      customizable: true,
      customizationOptions: [
        {
          name: 'Add Walnuts',
          type: 'checkbox' as const,
          options: ['Yes'],
          priceAdjustment: 1.5,
          required: false,
        },
      ],
      popularityScore: 58,
    },
    {
      name: 'Brioche Loaf',
      description: 'Rich, buttery French bread perfect for toast',
      category: 'bread' as const,
      status: 'active' as const,
      basePrice: '7.50',
      costOfGoods: '2.50',
      margin: '66.67',
      estimatedPrepTime: 240,
      allergens: ['gluten', 'dairy', 'eggs'],
      tags: ['french', 'premium', 'breakfast'],
      storageInstructions: 'Store in cool place',
      shelfLife: 72,
      minimumOrderQuantity: 1,
      customizable: false,
      popularityScore: 48,
    },

    // More Cookies
    {
      name: 'Peanut Butter Cookies',
      description: 'Classic peanut butter cookies with fork marks',
      category: 'cookie' as const,
      status: 'active' as const,
      basePrice: '11.50',
      costOfGoods: '4.20',
      margin: '63.48',
      estimatedPrepTime: 35,
      allergens: ['gluten', 'dairy', 'eggs', 'peanuts'],
      tags: ['classic', 'dozen', 'nut'],
      storageInstructions: 'Store in airtight container',
      shelfLife: 168,
      minimumOrderQuantity: 12,
      customizable: false,
      popularityScore: 60,
    },
    {
      name: 'Snickerdoodles',
      description: 'Soft cinnamon-sugar cookies with crispy edges',
      category: 'cookie' as const,
      status: 'active' as const,
      basePrice: '10.50',
      costOfGoods: '3.80',
      margin: '63.81',
      estimatedPrepTime: 32,
      allergens: ['gluten', 'dairy', 'eggs'],
      tags: ['classic', 'dozen', 'cinnamon'],
      storageInstructions: 'Store in airtight container',
      shelfLife: 168,
      minimumOrderQuantity: 12,
      customizable: false,
      popularityScore: 52,
    },
    {
      name: 'Brownie Squares',
      description: 'Fudgy chocolate brownies cut into squares',
      category: 'cookie' as const,
      status: 'active' as const,
      basePrice: '14.00',
      costOfGoods: '5.20',
      margin: '62.86',
      estimatedPrepTime: 50,
      allergens: ['gluten', 'dairy', 'eggs', 'soy'],
      tags: ['chocolate', 'fudgy', 'dozen'],
      storageInstructions: 'Store covered',
      shelfLife: 120,
      minimumOrderQuantity: 12,
      customizable: false,
      popularityScore: 78,
    },
    {
      name: 'Macaron Box (12pc)',
      description: 'Assorted French macarons in gift box',
      category: 'cookie' as const,
      status: 'active' as const,
      basePrice: '28.00',
      costOfGoods: '10.50',
      margin: '62.50',
      estimatedPrepTime: 105,
      allergens: ['eggs', 'nuts', 'dairy'],
      tags: ['french', 'premium', 'gift', 'gluten-free'],
      nutritionalInfo: {
        calories: 110,
        fat: 5,
        carbs: 14,
        protein: 2,
        sugar: 12,
      },
      storageInstructions: 'Refrigerate in box',
      shelfLife: 96,
      minimumOrderQuantity: 1,
      customizable: true,
      customizationOptions: [
        {
          name: 'Flavors',
          type: 'select' as const,
          options: ['Assorted', 'All Chocolate', 'All Vanilla', 'Fruit Mix'],
          required: true,
        },
      ],
      popularityScore: 65,
    },

    // More Cakes
    {
      name: 'Carrot Cake',
      description: 'Spiced carrot cake with cream cheese frosting',
      category: 'cake' as const,
      status: 'active' as const,
      basePrice: '50.00',
      costOfGoods: '19.50',
      margin: '61.00',
      estimatedPrepTime: 95,
      allergens: ['gluten', 'dairy', 'eggs', 'nuts'],
      tags: ['celebration', 'spiced', 'signature'],
      storageInstructions: 'Must be refrigerated',
      shelfLife: 96,
      minimumOrderQuantity: 1,
      customizable: true,
      customizationOptions: [
        {
          name: 'Size',
          type: 'select' as const,
          options: ['8 inch', '10 inch'],
          required: true,
        },
        {
          name: 'Message',
          type: 'text' as const,
          required: false,
        },
      ],
      popularityScore: 68,
    },
    {
      name: 'Lemon Cake',
      description: 'Light lemon cake with lemon buttercream',
      category: 'cake' as const,
      status: 'active' as const,
      basePrice: '44.00',
      costOfGoods: '17.00',
      margin: '61.36',
      estimatedPrepTime: 155,
      allergens: ['gluten', 'dairy', 'eggs'],
      tags: ['celebration', 'citrus', 'spring'],
      storageInstructions: 'Must be refrigerated',
      shelfLife: 72,
      minimumOrderQuantity: 1,
      customizable: true,
      customizationOptions: [
        {
          name: 'Size',
          type: 'select' as const,
          options: ['8 inch', '10 inch'],
          required: true,
        },
      ],
      popularityScore: 58,
    },
    {
      name: 'Tiramisu Cake',
      description: 'Italian coffee-soaked cake with mascarpone',
      category: 'cake' as const,
      status: 'active' as const,
      basePrice: '52.00',
      costOfGoods: '21.00',
      margin: '59.62',
      estimatedPrepTime: 90,
      allergens: ['gluten', 'dairy', 'eggs'],
      tags: ['italian', 'coffee', 'premium', 'no-bake'],
      storageInstructions: 'Must be refrigerated',
      shelfLife: 96,
      minimumOrderQuantity: 1,
      customizable: false,
      popularityScore: 62,
    },

    // More Sandwiches
    {
      name: 'Ham & Cheddar Croissant',
      description: 'Sliced ham and aged cheddar on butter croissant',
      category: 'sandwich' as const,
      status: 'active' as const,
      basePrice: '7.50',
      costOfGoods: '3.20',
      margin: '57.33',
      estimatedPrepTime: 8,
      allergens: ['gluten', 'dairy', 'eggs'],
      tags: ['breakfast', 'lunch', 'popular'],
      storageInstructions: 'Refrigerate immediately',
      shelfLife: 12,
      minimumOrderQuantity: 1,
      customizable: false,
      popularityScore: 55,
    },
    {
      name: 'Veggie Wrap',
      description: 'Hummus, fresh vegetables in whole wheat wrap',
      category: 'sandwich' as const,
      status: 'active' as const,
      basePrice: '7.75',
      costOfGoods: '3.10',
      margin: '60.00',
      estimatedPrepTime: 10,
      allergens: ['gluten'],
      tags: ['vegetarian', 'healthy', 'fresh'],
      storageInstructions: 'Refrigerate immediately',
      shelfLife: 8,
      minimumOrderQuantity: 1,
      customizable: false,
      popularityScore: 42,
    },
    {
      name: 'Chicken Pesto Panini',
      description: 'Grilled chicken, pesto, mozzarella on ciabatta',
      category: 'sandwich' as const,
      status: 'active' as const,
      basePrice: '9.75',
      costOfGoods: '4.00',
      margin: '58.97',
      estimatedPrepTime: 12,
      allergens: ['gluten', 'dairy', 'nuts'],
      tags: ['hot', 'italian', 'lunch'],
      storageInstructions: 'Serve hot, do not store',
      shelfLife: 2,
      minimumOrderQuantity: 1,
      customizable: false,
      popularityScore: 48,
    },

    // More Beverages
    {
      name: 'Hot Chocolate',
      description: 'Rich hot chocolate with whipped cream',
      category: 'beverage' as const,
      status: 'active' as const,
      basePrice: '4.25',
      costOfGoods: '1.20',
      margin: '71.76',
      estimatedPrepTime: 5,
      allergens: ['dairy', 'soy'],
      tags: ['hot', 'chocolate', 'winter'],
      storageInstructions: 'Serve immediately',
      shelfLife: 1,
      minimumOrderQuantity: 1,
      customizable: true,
      customizationOptions: [
        {
          name: 'Extras',
          type: 'checkbox' as const,
          options: ['Extra Whipped Cream', 'Marshmallows', 'Peppermint'],
          priceAdjustment: 0.5,
          required: false,
        },
      ],
      popularityScore: 65,
    },
    {
      name: 'Fresh Juice',
      description: 'Daily fresh-squeezed juice',
      category: 'beverage' as const,
      status: 'active' as const,
      basePrice: '5.50',
      costOfGoods: '2.00',
      margin: '63.64',
      estimatedPrepTime: 5,
      allergens: [],
      tags: ['fresh', 'healthy', 'juice'],
      storageInstructions: 'Keep refrigerated, serve cold',
      shelfLife: 24,
      minimumOrderQuantity: 1,
      customizable: true,
      customizationOptions: [
        {
          name: 'Type',
          type: 'select' as const,
          options: ['Orange', 'Apple', 'Carrot', 'Green Mix'],
          required: true,
        },
      ],
      popularityScore: 52,
    },
    {
      name: 'Iced Tea',
      description: 'Freshly brewed iced tea, sweetened or unsweetened',
      category: 'beverage' as const,
      status: 'active' as const,
      basePrice: '3.25',
      costOfGoods: '0.75',
      margin: '76.92',
      estimatedPrepTime: 3,
      allergens: [],
      tags: ['cold', 'refreshing', 'tea'],
      storageInstructions: 'Serve cold',
      shelfLife: 8,
      minimumOrderQuantity: 1,
      customizable: true,
      customizationOptions: [
        {
          name: 'Type',
          type: 'select' as const,
          options: ['Sweet', 'Unsweet', 'Lemon', 'Peach'],
          required: true,
        },
      ],
      popularityScore: 58,
    },

    // Seasonal
    {
      name: 'Pumpkin Spice Muffin',
      description: 'Seasonal pumpkin muffin with cream cheese frosting',
      category: 'seasonal' as const,
      status: 'seasonal' as const,
      basePrice: '4.50',
      costOfGoods: '1.60',
      margin: '64.44',
      estimatedPrepTime: 35,
      allergens: ['gluten', 'dairy', 'eggs'],
      tags: ['fall', 'pumpkin', 'limited'],
      availableSeasons: ['Fall', 'October', 'November'],
      storageInstructions: 'Store at room temperature',
      shelfLife: 48,
      minimumOrderQuantity: 1,
      customizable: false,
      popularityScore: 72,
    },
    {
      name: 'Gingerbread Cookies',
      description: 'Holiday spiced gingerbread cookies',
      category: 'seasonal' as const,
      status: 'seasonal' as const,
      basePrice: '13.50',
      costOfGoods: '4.80',
      margin: '64.44',
      estimatedPrepTime: 60,
      allergens: ['gluten', 'dairy', 'eggs'],
      tags: ['holiday', 'christmas', 'spiced', 'dozen'],
      availableSeasons: ['Winter', 'December'],
      storageInstructions: 'Store in airtight container',
      shelfLife: 240,
      minimumOrderQuantity: 12,
      customizable: true,
      customizationOptions: [
        {
          name: 'Decoration',
          type: 'select' as const,
          options: ['Plain', 'Iced', 'Decorated'],
          priceAdjustment: 2,
          required: true,
        },
      ],
      popularityScore: 80,
    },
  ];

  try {
    await db.insert(products).values(sampleProducts);
    console.log(`✅ Successfully seeded ${sampleProducts.length} products`);
  } catch (error) {
    console.error('❌ Error seeding products:', error);
    throw error;
  }
}
