import { NodePgDatabase } from 'drizzle-orm/node-postgres';
import { eq, sql } from 'drizzle-orm';
import { recipes, recipeIngredients, inventoryItems } from '../schemas';
import * as schema from '../schemas';

export async function seedRecipes(db: NodePgDatabase<typeof schema>) {
  console.log('🌱 Seeding recipes...');

  // Check existing recipes to prevent duplicates
  const existingRecipes = await db.select().from(recipes);
  const existingRecipeNames = new Set(existingRecipes.map(r => r.name));

  // First, get inventory items to reference as ingredients
  const inventory = await db.select().from(inventoryItems);

  // Create a map for easy lookup
  const getInventoryId = (name: string) => {
    const item = inventory.find((i) => i.name === name);
    if (!item) {
      console.warn(`⚠️  Inventory item not found: ${name}`);
      return null;
    }
    return item.id;
  };

  // Define all recipes to seed
  const recipesToSeed = [
      // ========== BREAD RECIPES ==========
      {
        name: 'Classic Sourdough Bread',
        category: 'bread',
        description:
          'Traditional artisan sourdough with a crispy crust and tangy flavor',
        prepTime: 240, // 4 hours (including fermentation)
        cookTime: 45,
        yield: 2,
        yieldUnit: 'loaves',
        costPerUnit: '1.8750', // Will be recalculated
        sellingPrice: '6.99',
        instructions: [
          'Mix flour, water, and sourdough starter until combined',
          'Autolyse for 30 minutes',
          'Add salt and knead for 10 minutes',
          'Bulk fermentation for 3-4 hours with folds every 30 minutes',
          'Shape into loaves and proof for 2 hours',
          'Score the top and bake at 230°C for 45 minutes',
        ],
        nutritionalInfo: {
          calories: 250,
          protein: 8,
          carbs: 52,
          fat: 1,
          sugar: 1,
          sodium: 450,
        },
        allergens: ['gluten'],
        tags: ['artisan', 'popular', 'signature'],
        isActive: true,
      },
      {
        name: 'French Baguette',
        category: 'bread',
        description: 'Crispy French baguette with airy crumb',
        prepTime: 180,
        cookTime: 25,
        yield: 3,
        yieldUnit: 'baguettes',
        costPerUnit: '0.8333',
        sellingPrice: '3.49',
        instructions: [
          'Mix bread flour, water, yeast, and salt',
          'Knead for 15 minutes until smooth',
          'First rise for 1 hour',
          'Divide and shape into baguettes',
          'Second rise for 45 minutes',
          'Score and bake at 240°C for 25 minutes',
        ],
        nutritionalInfo: {
          calories: 230,
          protein: 7,
          carbs: 48,
          fat: 1,
        },
        allergens: ['gluten'],
        tags: ['classic', 'french'],
        isActive: true,
      },
      {
        name: 'Whole Wheat Sandwich Bread',
        category: 'bread',
        description: 'Hearty whole wheat bread perfect for sandwiches',
        prepTime: 150,
        cookTime: 35,
        yield: 1,
        yieldUnit: 'loaf',
        costPerUnit: '2.1500',
        sellingPrice: '5.99',
        instructions: [
          'Mix whole wheat flour, water, honey, yeast, and salt',
          'Knead for 10 minutes',
          'First rise for 1.5 hours',
          'Shape into loaf pan',
          'Second rise for 45 minutes',
          'Bake at 190°C for 35 minutes',
        ],
        nutritionalInfo: {
          calories: 220,
          protein: 9,
          carbs: 42,
          fat: 2,
          sugar: 3,
        },
        allergens: ['gluten'],
        tags: ['healthy', 'sandwich'],
        isActive: true,
      },

      // ========== PASTRY RECIPES ==========
      {
        name: 'Butter Croissants',
        category: 'pastry',
        description: 'Flaky, buttery French croissants',
        prepTime: 420, // 7 hours (with resting time)
        cookTime: 20,
        yield: 12,
        yieldUnit: 'pieces',
        costPerUnit: '0.4583',
        sellingPrice: '2.99',
        instructions: [
          'Make dough with flour, milk, yeast, sugar, and salt',
          'Laminate with butter through 3 folds',
          'Rest in fridge between each fold (1 hour each)',
          'Roll out and cut into triangles',
          'Shape into croissants and proof for 2 hours',
          'Egg wash and bake at 200°C for 20 minutes',
        ],
        nutritionalInfo: {
          calories: 280,
          protein: 5,
          carbs: 28,
          fat: 16,
        },
        allergens: ['gluten', 'dairy', 'eggs'],
        tags: ['premium', 'popular', 'french'],
        isActive: true,
      },
      {
        name: 'Chocolate Chip Cookies',
        category: 'cookie',
        description: 'Classic chocolate chip cookies with a crispy edge and chewy center',
        prepTime: 15,
        cookTime: 12,
        yield: 24,
        yieldUnit: 'cookies',
        costPerUnit: '0.2917',
        sellingPrice: '1.49',
        instructions: [
          'Cream butter and sugars until fluffy',
          'Beat in eggs and vanilla extract',
          'Mix in flour, baking soda, and salt',
          'Fold in chocolate chips',
          'Scoop onto baking sheets',
          'Bake at 180°C for 12 minutes',
        ],
        nutritionalInfo: {
          calories: 180,
          protein: 2,
          carbs: 24,
          fat: 9,
          sugar: 15,
        },
        allergens: ['gluten', 'dairy', 'eggs'],
        tags: ['classic', 'popular', 'kids'],
        isActive: true,
      },

      // ========== CAKE RECIPES ==========
      {
        name: 'Classic Vanilla Cake',
        category: 'cake',
        description: 'Moist vanilla layer cake perfect for celebrations',
        prepTime: 30,
        cookTime: 35,
        yield: 1,
        yieldUnit: '9-inch cake',
        costPerUnit: '8.7500',
        sellingPrice: '35.00',
        instructions: [
          'Cream butter and sugar until light and fluffy',
          'Add eggs one at a time, beating well',
          'Mix in vanilla extract',
          'Alternate adding flour mixture and milk',
          'Pour into prepared pans',
          'Bake at 175°C for 35 minutes',
          'Cool completely before frosting',
        ],
        nutritionalInfo: {
          calories: 380,
          protein: 5,
          carbs: 52,
          fat: 18,
          sugar: 32,
        },
        allergens: ['gluten', 'dairy', 'eggs'],
        tags: ['celebration', 'custom'],
        isActive: true,
      },
      {
        name: 'Dark Chocolate Cake',
        category: 'cake',
        description: 'Rich, decadent chocolate cake with deep cocoa flavor',
        prepTime: 40,
        cookTime: 40,
        yield: 1,
        yieldUnit: '9-inch cake',
        costPerUnit: '10.2500',
        sellingPrice: '42.00',
        instructions: [
          'Mix flour, cocoa powder, baking soda, and salt',
          'Cream butter and sugar',
          'Add eggs, vanilla, and coffee',
          'Alternate dry ingredients with buttermilk',
          'Pour into prepared pans',
          'Bake at 175°C for 40 minutes',
          'Cool and frost with chocolate ganache',
        ],
        nutritionalInfo: {
          calories: 420,
          protein: 6,
          carbs: 58,
          fat: 20,
          sugar: 38,
        },
        allergens: ['gluten', 'dairy', 'eggs'],
        tags: ['premium', 'celebration', 'chocolate'],
        isActive: true,
      },
      {
        name: 'Vanilla Birthday Cake',
        category: 'cake',
        description: 'Festive vanilla layer cake with buttercream frosting, perfect for celebrations',
        prepTime: 45,
        cookTime: 35,
        yield: 1,
        yieldUnit: '9-inch cake',
        costPerUnit: '11.7500',
        sellingPrice: '48.00',
        instructions: [
          'Preheat oven to 175°C and prepare cake pans',
          'Cream butter and sugar until light and fluffy',
          'Add eggs one at a time, then vanilla extract',
          'Combine flour, baking powder, and salt',
          'Alternate adding dry ingredients with milk',
          'Divide batter between pans and bake for 35 minutes',
          'Cool completely before frosting with vanilla buttercream',
          'Decorate with sprinkles and birthday candles',
        ],
        nutritionalInfo: {
          calories: 385,
          protein: 5,
          carbs: 52,
          fat: 18,
          sugar: 35,
        },
        allergens: ['gluten', 'dairy', 'eggs'],
        tags: ['celebration', 'birthday', 'custom', 'popular'],
        isActive: true,
      },

      // ========== SPECIALTY ITEMS ==========
      {
        name: 'Cinnamon Rolls',
        category: 'pastry',
        description: 'Soft, fluffy cinnamon rolls with cream cheese frosting',
        prepTime: 180,
        cookTime: 25,
        yield: 12,
        yieldUnit: 'rolls',
        costPerUnit: '0.5417',
        sellingPrice: '3.99',
        instructions: [
          'Make enriched dough with flour, milk, butter, eggs, and yeast',
          'First rise for 1 hour',
          'Roll out and spread with cinnamon-butter mixture',
          'Roll up and cut into 12 pieces',
          'Second rise for 45 minutes',
          'Bake at 180°C for 25 minutes',
          'Top with cream cheese frosting while warm',
        ],
        nutritionalInfo: {
          calories: 340,
          protein: 5,
          carbs: 48,
          fat: 14,
          sugar: 22,
        },
        allergens: ['gluten', 'dairy', 'eggs'],
        tags: ['popular', 'breakfast', 'sweet'],
        isActive: true,
      },
      {
        name: 'Pain au Chocolat',
        category: 'pastry',
        description: 'Buttery croissant dough wrapped around dark chocolate batons',
        prepTime: 420,
        cookTime: 18,
        yield: 12,
        yieldUnit: 'pieces',
        costPerUnit: '0.6250',
        sellingPrice: '3.25',
        instructions: [
          'Prepare laminated croissant dough with butter layers',
          'Roll out dough and cut into rectangles',
          'Place chocolate batons on each rectangle',
          'Roll tightly and seal edges',
          'Proof for 2 hours at room temperature',
          'Egg wash and bake at 200°C for 18 minutes',
        ],
        nutritionalInfo: {
          calories: 310,
          protein: 6,
          carbs: 35,
          fat: 18,
          sugar: 12,
        },
        allergens: ['gluten', 'dairy', 'eggs', 'soy'],
        tags: ['french', 'chocolate', 'premium'],
        isActive: true,
      },
      {
        name: 'Blueberry Muffins',
        category: 'pastry',
        description: 'Moist muffins bursting with fresh blueberries and streusel topping',
        prepTime: 20,
        cookTime: 22,
        yield: 12,
        yieldUnit: 'muffins',
        costPerUnit: '0.4583',
        sellingPrice: '2.75',
        instructions: [
          'Mix dry ingredients: flour, sugar, baking powder, salt',
          'Combine wet ingredients: eggs, milk, melted butter, vanilla',
          'Fold wet into dry ingredients until just combined',
          'Gently fold in fresh blueberries',
          'Fill muffin tins 3/4 full',
          'Top with streusel mixture',
          'Bake at 190°C for 22 minutes until golden',
        ],
        nutritionalInfo: {
          calories: 240,
          protein: 4,
          carbs: 38,
          fat: 8,
          sugar: 18,
        },
        allergens: ['gluten', 'dairy', 'eggs'],
        tags: ['breakfast', 'fruit', 'popular'],
        isActive: true,
      },
      {
        name: 'Carrot Cake',
        category: 'cake',
        description: 'Spiced carrot cake with cream cheese frosting and walnuts',
        prepTime: 45,
        cookTime: 50,
        yield: 1,
        yieldUnit: '9-inch cake',
        costPerUnit: '12.5000',
        sellingPrice: '48.00',
        instructions: [
          'Mix flour, baking soda, cinnamon, nutmeg, and salt',
          'Beat eggs with oil and sugars until smooth',
          'Fold in grated carrots, crushed pineapple, and walnuts',
          'Combine wet and dry ingredients',
          'Pour into prepared pans',
          'Bake at 175°C for 50 minutes',
          'Cool completely before frosting with cream cheese frosting',
        ],
        nutritionalInfo: {
          calories: 410,
          protein: 5,
          carbs: 52,
          fat: 21,
          sugar: 35,
        },
        allergens: ['gluten', 'dairy', 'eggs', 'nuts'],
        tags: ['celebration', 'signature', 'spiced'],
        isActive: true,
      },
      {
        name: 'Lemon Tart',
        category: 'pastry',
        description: 'Tangy lemon curd in a buttery shortbread crust',
        prepTime: 60,
        cookTime: 35,
        yield: 8,
        yieldUnit: 'slices',
        costPerUnit: '1.8750',
        sellingPrice: '6.50',
        instructions: [
          'Make shortbread crust with butter, sugar, and flour',
          'Press into tart pan and blind bake at 180°C for 15 minutes',
          'Prepare lemon curd with lemon juice, zest, eggs, sugar, and butter',
          'Cook curd over double boiler until thick',
          'Pour into baked crust',
          'Bake for 20 minutes until just set',
          'Chill completely before slicing',
        ],
        nutritionalInfo: {
          calories: 320,
          protein: 4,
          carbs: 42,
          fat: 16,
          sugar: 28,
        },
        allergens: ['gluten', 'dairy', 'eggs'],
        tags: ['french', 'citrus', 'elegant'],
        isActive: true,
      },
      {
        name: 'Banana Bread',
        category: 'bread',
        description: 'Moist banana bread with optional chocolate chips or walnuts',
        prepTime: 15,
        cookTime: 60,
        yield: 1,
        yieldUnit: 'loaf',
        costPerUnit: '2.2500',
        sellingPrice: '7.99',
        instructions: [
          'Mash ripe bananas until smooth',
          'Mix in melted butter, sugar, egg, and vanilla',
          'Combine flour, baking soda, and salt',
          'Fold dry ingredients into banana mixture',
          'Optional: add chocolate chips or walnuts',
          'Pour into greased loaf pan',
          'Bake at 175°C for 60 minutes until toothpick comes out clean',
        ],
        nutritionalInfo: {
          calories: 280,
          protein: 4,
          carbs: 45,
          fat: 10,
          sugar: 24,
        },
        allergens: ['gluten', 'dairy', 'eggs'],
        tags: ['quick bread', 'banana', 'comfort'],
        isActive: true,
      },
      {
        name: 'Macaron Assortment',
        category: 'cookie',
        description: 'Delicate French macarons in assorted flavors',
        prepTime: 90,
        cookTime: 15,
        yield: 24,
        yieldUnit: 'macarons',
        costPerUnit: '0.7917',
        sellingPrice: '2.50',
        instructions: [
          'Sift almond flour and powdered sugar together three times',
          'Make French meringue with egg whites and granulated sugar',
          'Fold dry ingredients into meringue using macaronage technique',
          'Pipe circles onto parchment-lined baking sheets',
          'Let dry for 30 minutes until skin forms',
          'Bake at 150°C for 15 minutes',
          'Cool completely before filling with buttercream or ganache',
        ],
        nutritionalInfo: {
          calories: 110,
          protein: 2,
          carbs: 14,
          fat: 5,
          sugar: 12,
        },
        allergens: ['eggs', 'nuts', 'dairy'],
        tags: ['french', 'premium', 'elegant', 'gluten-free'],
        isActive: true,
      },
      {
        name: 'Brownies',
        category: 'cookie',
        description: 'Fudgy chocolate brownies with a crackly top',
        prepTime: 20,
        cookTime: 30,
        yield: 16,
        yieldUnit: 'brownies',
        costPerUnit: '0.4375',
        sellingPrice: '2.50',
        instructions: [
          'Melt butter and dark chocolate together',
          'Whisk in sugar, eggs, and vanilla until smooth',
          'Fold in flour, cocoa powder, and salt',
          'Pour into greased 9x13 pan',
          'Optional: swirl in peanut butter or add chocolate chips',
          'Bake at 175°C for 30 minutes',
          'Cool completely before cutting',
        ],
        nutritionalInfo: {
          calories: 220,
          protein: 3,
          carbs: 28,
          fat: 12,
          sugar: 20,
        },
        allergens: ['gluten', 'dairy', 'eggs', 'soy'],
        tags: ['chocolate', 'fudgy', 'popular'],
        isActive: true,
      },
      {
        name: 'Focaccia',
        category: 'bread',
        description: 'Italian flatbread with herbs, olive oil, and sea salt',
        prepTime: 150,
        cookTime: 25,
        yield: 1,
        yieldUnit: 'sheet',
        costPerUnit: '2.8000',
        sellingPrice: '8.99',
        instructions: [
          'Mix bread flour, water, yeast, olive oil, and salt',
          'Knead until smooth and elastic',
          'First rise for 1 hour',
          'Stretch dough in oiled baking sheet',
          'Dimple surface with fingers',
          'Drizzle with olive oil, add rosemary and sea salt',
          'Second rise for 30 minutes',
          'Bake at 220°C for 25 minutes until golden',
        ],
        nutritionalInfo: {
          calories: 210,
          protein: 6,
          carbs: 35,
          fat: 6,
          sugar: 1,
        },
        allergens: ['gluten'],
        tags: ['italian', 'artisan', 'savory'],
        isActive: true,
      },
      {
        name: 'Apple Pie',
        category: 'pastry',
        description: 'Classic double-crust apple pie with cinnamon and brown sugar',
        prepTime: 60,
        cookTime: 55,
        yield: 8,
        yieldUnit: 'slices',
        costPerUnit: '2.2500',
        sellingPrice: '7.99',
        instructions: [
          'Make pie dough with flour, butter, salt, and ice water',
          'Chill dough for 30 minutes',
          'Peel and slice apples, toss with sugar, cinnamon, and lemon juice',
          'Roll out bottom crust and place in pie dish',
          'Fill with apple mixture and dot with butter',
          'Cover with top crust, crimp edges, and cut vents',
          'Brush with egg wash and sprinkle with sugar',
          'Bake at 190°C for 55 minutes until golden and bubbling',
        ],
        nutritionalInfo: {
          calories: 340,
          protein: 3,
          carbs: 52,
          fat: 14,
          sugar: 28,
        },
        allergens: ['gluten', 'dairy', 'eggs'],
        tags: ['classic', 'fruit', 'american'],
        isActive: true,
      },
      {
        name: 'Eclair',
        category: 'pastry',
        description: 'Choux pastry filled with vanilla cream and topped with chocolate',
        prepTime: 90,
        cookTime: 35,
        yield: 12,
        yieldUnit: 'eclairs',
        costPerUnit: '0.7083',
        sellingPrice: '3.75',
        instructions: [
          'Make choux pastry with water, butter, flour, and eggs',
          'Pipe 4-inch logs onto baking sheet',
          'Bake at 200°C for 30 minutes until puffed and golden',
          'Cool completely',
          'Make vanilla pastry cream',
          'Fill eclairs with cream using piping bag',
          'Dip tops in chocolate ganache',
          'Refrigerate until serving',
        ],
        nutritionalInfo: {
          calories: 285,
          protein: 5,
          carbs: 32,
          fat: 15,
          sugar: 18,
        },
        allergens: ['gluten', 'dairy', 'eggs', 'soy'],
        tags: ['french', 'elegant', 'cream'],
        isActive: true,
      },
      {
        name: 'Tiramisu',
        category: 'cake',
        description: 'Italian coffee-flavored dessert with mascarpone cream',
        prepTime: 45,
        cookTime: 0,
        yield: 12,
        yieldUnit: 'servings',
        costPerUnit: '1.9167',
        sellingPrice: '6.99',
        instructions: [
          'Brew strong espresso and let cool',
          'Whisk egg yolks with sugar until thick',
          'Fold in mascarpone cheese',
          'Whip heavy cream to stiff peaks',
          'Fold whipped cream into mascarpone mixture',
          'Dip ladyfinger cookies in espresso',
          'Layer cookies and cream in dish',
          'Dust with cocoa powder and refrigerate overnight',
        ],
        nutritionalInfo: {
          calories: 380,
          protein: 7,
          carbs: 35,
          fat: 24,
          sugar: 22,
        },
        allergens: ['gluten', 'dairy', 'eggs'],
        tags: ['italian', 'coffee', 'no-bake', 'premium'],
        isActive: true,
      },

      // ========== ADDITIONAL BREAD RECIPES ==========
      {
        name: 'Ciabatta',
        category: 'bread',
        description: 'Italian white bread with a soft, porous interior and crispy crust',
        prepTime: 240,
        cookTime: 30,
        yield: 2,
        yieldUnit: 'loaves',
        costPerUnit: '2.0000',
        sellingPrice: '5.25',
        instructions: [
          'Mix bread flour, water, yeast, and salt until combined',
          'Autolyse for 30 minutes',
          'Knead gently to develop gluten',
          'First rise for 2 hours with stretch and folds',
          'Shape into ciabatta loaves on floured surface',
          'Second rise for 1 hour',
          'Bake at 220°C for 30 minutes with steam',
        ],
        nutritionalInfo: {
          calories: 220,
          protein: 7,
          carbs: 44,
          fat: 1,
        },
        allergens: ['gluten'],
        tags: ['italian', 'artisan'],
        isActive: true,
      },
      {
        name: 'Brioche Loaf',
        category: 'bread',
        description: 'Rich, buttery French bread with a tender crumb',
        prepTime: 180,
        cookTime: 35,
        yield: 1,
        yieldUnit: 'loaf',
        costPerUnit: '3.2500',
        sellingPrice: '7.99',
        instructions: [
          'Mix bread flour, eggs, sugar, yeast, and milk',
          'Knead for 10 minutes',
          'Gradually add softened butter while kneading',
          'First rise for 2 hours until doubled',
          'Shape into loaf pan',
          'Second rise for 1 hour',
          'Egg wash and bake at 180°C for 35 minutes',
        ],
        nutritionalInfo: {
          calories: 310,
          protein: 8,
          carbs: 42,
          fat: 12,
          sugar: 8,
        },
        allergens: ['gluten', 'dairy', 'eggs'],
        tags: ['french', 'rich', 'premium'],
        isActive: true,
      },

      // ========== ADDITIONAL PASTRY RECIPES ==========
      {
        name: 'Almond Croissant',
        category: 'pastry',
        description: 'Butter croissant filled with almond cream and topped with sliced almonds',
        prepTime: 120,
        cookTime: 15,
        yield: 8,
        yieldUnit: 'croissants',
        costPerUnit: '1.8000',
        sellingPrice: '4.75',
        instructions: [
          'Make almond cream by mixing butter, sugar, almond flour, and eggs',
          'Slice day-old croissants horizontally',
          'Spread almond cream inside and on top',
          'Sprinkle with sliced almonds',
          'Dust with powdered sugar',
          'Bake at 180°C for 15 minutes until golden',
        ],
        nutritionalInfo: {
          calories: 420,
          protein: 9,
          carbs: 38,
          fat: 26,
          sugar: 16,
        },
        allergens: ['gluten', 'dairy', 'eggs', 'nuts'],
        tags: ['french', 'premium', 'almonds'],
        isActive: true,
      },
      {
        name: 'Danish Pastry',
        category: 'pastry',
        description: 'Flaky laminated pastry with sweet fruit or cream fillings',
        prepTime: 150,
        cookTime: 18,
        yield: 12,
        yieldUnit: 'pastries',
        costPerUnit: '1.5000',
        sellingPrice: '4.25',
        instructions: [
          'Make laminated dough with butter layers',
          'Roll and fold 3 times for flaky layers',
          'Cut into squares or rounds',
          'Add fruit filling (cherry, apple, or cream cheese)',
          'Shape and seal edges',
          'Egg wash and bake at 200°C for 18 minutes',
          'Glaze with apricot jam while warm',
        ],
        nutritionalInfo: {
          calories: 310,
          protein: 5,
          carbs: 42,
          fat: 14,
          sugar: 18,
        },
        allergens: ['gluten', 'dairy', 'eggs'],
        tags: ['danish', 'fruit', 'breakfast'],
        isActive: true,
      },
      {
        name: 'Mixed Berry Scone',
        category: 'pastry',
        description: 'Buttery scone studded with fresh mixed berries',
        prepTime: 20,
        cookTime: 18,
        yield: 8,
        yieldUnit: 'scones',
        costPerUnit: '1.1000',
        sellingPrice: '3.75',
        instructions: [
          'Mix flour, sugar, baking powder, and salt',
          'Cut in cold butter until crumbly',
          'Add cream and mix until just combined',
          'Fold in fresh berries gently',
          'Pat dough into circle and cut into wedges',
          'Brush with cream and sprinkle with sugar',
          'Bake at 200°C for 18 minutes',
        ],
        nutritionalInfo: {
          calories: 280,
          protein: 4,
          carbs: 38,
          fat: 12,
          sugar: 12,
        },
        allergens: ['gluten', 'dairy'],
        tags: ['british', 'berries', 'breakfast'],
        isActive: true,
      },

      // ========== ADDITIONAL COOKIE RECIPES ==========
      {
        name: 'Oatmeal Raisin Cookies',
        category: 'cookie',
        description: 'Chewy oatmeal cookies with plump raisins and warm spices',
        prepTime: 15,
        cookTime: 12,
        yield: 24,
        yieldUnit: 'cookies',
        costPerUnit: '0.3500',
        sellingPrice: '2.25',
        instructions: [
          'Cream butter and sugars',
          'Add eggs and vanilla',
          'Mix in flour, oats, cinnamon, and baking soda',
          'Fold in raisins',
          'Scoop onto baking sheets',
          'Bake at 175°C for 12 minutes',
        ],
        nutritionalInfo: {
          calories: 150,
          protein: 2,
          carbs: 22,
          fat: 6,
          sugar: 12,
        },
        allergens: ['gluten', 'dairy', 'eggs'],
        tags: ['oatmeal', 'raisins', 'classic'],
        isActive: true,
      },
      {
        name: 'Sugar Cookies',
        category: 'cookie',
        description: 'Classic buttery sugar cookies, perfect for decorating',
        prepTime: 30,
        cookTime: 10,
        yield: 36,
        yieldUnit: 'cookies',
        costPerUnit: '0.2500',
        sellingPrice: '1.99',
        instructions: [
          'Cream butter and sugar until fluffy',
          'Add egg and vanilla',
          'Mix in flour, baking powder, and salt',
          'Chill dough for 1 hour',
          'Roll out and cut into shapes',
          'Bake at 175°C for 10 minutes',
          'Cool and decorate as desired',
        ],
        nutritionalInfo: {
          calories: 120,
          protein: 1,
          carbs: 16,
          fat: 6,
          sugar: 8,
        },
        allergens: ['gluten', 'dairy', 'eggs'],
        tags: ['classic', 'decorating', 'holiday'],
        isActive: true,
      },
      {
        name: 'Peanut Butter Cookies',
        category: 'cookie',
        description: 'Soft and chewy peanut butter cookies with signature fork marks',
        prepTime: 15,
        cookTime: 12,
        yield: 24,
        yieldUnit: 'cookies',
        costPerUnit: '0.4000',
        sellingPrice: '2.50',
        instructions: [
          'Mix peanut butter, butter, and sugars',
          'Add egg and vanilla',
          'Mix in flour, baking soda, and salt',
          'Roll into balls',
          'Press with fork in crisscross pattern',
          'Bake at 175°C for 12 minutes',
        ],
        nutritionalInfo: {
          calories: 165,
          protein: 4,
          carbs: 18,
          fat: 9,
          sugar: 10,
        },
        allergens: ['gluten', 'dairy', 'eggs', 'peanuts'],
        tags: ['peanut butter', 'classic'],
        isActive: true,
      },
      {
        name: 'Snickerdoodles',
        category: 'cookie',
        description: 'Soft cinnamon-sugar cookies with a tangy cream of tartar flavor',
        prepTime: 20,
        cookTime: 10,
        yield: 30,
        yieldUnit: 'cookies',
        costPerUnit: '0.2800',
        sellingPrice: '2.25',
        instructions: [
          'Cream butter and sugar',
          'Add eggs and vanilla',
          'Mix in flour, cream of tartar, baking soda, and salt',
          'Chill dough for 30 minutes',
          'Roll into balls and coat in cinnamon sugar',
          'Bake at 190°C for 10 minutes',
        ],
        nutritionalInfo: {
          calories: 135,
          protein: 2,
          carbs: 19,
          fat: 6,
          sugar: 11,
        },
        allergens: ['gluten', 'dairy', 'eggs'],
        tags: ['cinnamon', 'classic', 'tangy'],
        isActive: true,
      },
      {
        name: 'Gingerbread Cookies',
        category: 'cookie',
        description: 'Spiced molasses cookies perfect for holidays',
        prepTime: 40,
        cookTime: 10,
        yield: 24,
        yieldUnit: 'cookies',
        costPerUnit: '0.3200',
        sellingPrice: '2.50',
        instructions: [
          'Mix butter, molasses, and brown sugar',
          'Add egg',
          'Mix in flour, ginger, cinnamon, cloves, and baking soda',
          'Chill dough for 2 hours',
          'Roll out and cut into shapes',
          'Bake at 175°C for 10 minutes',
          'Decorate with royal icing',
        ],
        nutritionalInfo: {
          calories: 145,
          protein: 2,
          carbs: 22,
          fat: 6,
          sugar: 12,
        },
        allergens: ['gluten', 'dairy', 'eggs'],
        tags: ['holiday', 'spiced', 'decorating'],
        isActive: true,
      },
      {
        name: 'Brownie Squares',
        category: 'cookie',
        description: 'Fudgy chocolate brownies cut into perfect squares',
        prepTime: 15,
        cookTime: 25,
        yield: 16,
        yieldUnit: 'squares',
        costPerUnit: '0.5500',
        sellingPrice: '3.25',
        instructions: [
          'Melt butter and chocolate together',
          'Whisk in sugar and eggs',
          'Fold in flour and cocoa powder',
          'Pour into lined pan',
          'Bake at 175°C for 25 minutes',
          'Cool completely before cutting',
        ],
        nutritionalInfo: {
          calories: 220,
          protein: 3,
          carbs: 28,
          fat: 12,
          sugar: 20,
        },
        allergens: ['gluten', 'dairy', 'eggs'],
        tags: ['chocolate', 'fudgy', 'dessert'],
        isActive: true,
      },

      // ========== ADDITIONAL CAKE RECIPES ==========
      {
        name: 'Red Velvet Cake',
        category: 'cake',
        description: 'Striking red cake with cream cheese frosting',
        prepTime: 40,
        cookTime: 30,
        yield: 12,
        yieldUnit: 'slices',
        costPerUnit: '2.1500',
        sellingPrice: '6.99',
        instructions: [
          'Mix flour, cocoa, baking soda, and salt',
          'Cream butter and sugar',
          'Add eggs, buttermilk, red food coloring, and vinegar',
          'Fold in dry ingredients',
          'Pour into two 9-inch pans',
          'Bake at 175°C for 30 minutes',
          'Cool and frost with cream cheese frosting',
        ],
        nutritionalInfo: {
          calories: 380,
          protein: 5,
          carbs: 52,
          fat: 18,
          sugar: 36,
        },
        allergens: ['gluten', 'dairy', 'eggs'],
        tags: ['red velvet', 'cream cheese', 'celebration'],
        isActive: true,
      },
      {
        name: 'Lemon Cake',
        category: 'cake',
        description: 'Light and tangy lemon cake with lemon glaze',
        prepTime: 30,
        cookTime: 35,
        yield: 10,
        yieldUnit: 'slices',
        costPerUnit: '1.8500',
        sellingPrice: '5.99',
        instructions: [
          'Cream butter and sugar',
          'Add eggs, lemon zest, and lemon juice',
          'Mix in flour, baking powder, and salt',
          'Pour into loaf pan',
          'Bake at 175°C for 35 minutes',
          'Make lemon glaze with powdered sugar and lemon juice',
          'Poke holes in warm cake and pour glaze over',
        ],
        nutritionalInfo: {
          calories: 310,
          protein: 4,
          carbs: 48,
          fat: 12,
          sugar: 32,
        },
        allergens: ['gluten', 'dairy', 'eggs'],
        tags: ['lemon', 'citrus', 'glazed'],
        isActive: true,
      },
      {
        name: 'Tiramisu Cake',
        category: 'cake',
        description: 'Layered coffee-soaked cake with mascarpone cream',
        prepTime: 60,
        cookTime: 25,
        yield: 12,
        yieldUnit: 'slices',
        costPerUnit: '2.4000',
        sellingPrice: '7.99',
        instructions: [
          'Bake vanilla sponge cake layers',
          'Prepare coffee syrup with espresso and sugar',
          'Make mascarpone cream with whipped cream and sugar',
          'Soak cake layers in coffee syrup',
          'Layer cake with mascarpone cream',
          'Refrigerate for 4 hours',
          'Dust with cocoa powder before serving',
        ],
        nutritionalInfo: {
          calories: 395,
          protein: 7,
          carbs: 38,
          fat: 24,
          sugar: 24,
        },
        allergens: ['gluten', 'dairy', 'eggs'],
        tags: ['italian', 'coffee', 'layered', 'premium'],
        isActive: true,
      },
      {
        name: 'Macaron',
        category: 'cookie',
        description: 'Delicate French almond meringue cookies with various fillings',
        prepTime: 90,
        cookTime: 15,
        yield: 24,
        yieldUnit: 'macarons',
        costPerUnit: '0.8500',
        sellingPrice: '3.50',
        instructions: [
          'Make almond flour and powdered sugar mixture',
          'Whip egg whites to stiff peaks with granulated sugar',
          'Fold dry ingredients into meringue (macaronage)',
          'Pipe rounds onto parchment',
          'Rest for 30 minutes to form skin',
          'Bake at 150°C for 15 minutes',
          'Fill with buttercream or ganache',
        ],
        nutritionalInfo: {
          calories: 90,
          protein: 2,
          carbs: 12,
          fat: 4,
          sugar: 11,
        },
        allergens: ['eggs', 'nuts', 'dairy'],
        tags: ['french', 'elegant', 'almond', 'premium'],
        isActive: true,
      },

      // ========== SANDWICH RECIPES ==========
      {
        name: 'Turkey Swiss Sandwich',
        category: 'sandwich',
        description: 'Classic turkey and Swiss cheese sandwich on artisan bread',
        prepTime: 10,
        cookTime: 0,
        yield: 1,
        yieldUnit: 'sandwich',
        costPerUnit: '2.8000',
        sellingPrice: '8.99',
        instructions: [
          'Slice artisan bread',
          'Layer sliced turkey breast',
          'Add Swiss cheese',
          'Top with lettuce, tomato, and red onion',
          'Spread mayonnaise and mustard',
          'Assemble sandwich',
        ],
        nutritionalInfo: {
          calories: 450,
          protein: 32,
          carbs: 42,
          fat: 16,
          sodium: 950,
        },
        allergens: ['gluten', 'dairy'],
        tags: ['sandwich', 'turkey', 'lunch'],
        isActive: true,
      },
      {
        name: 'Caprese Sandwich',
        category: 'sandwich',
        description: 'Italian-style sandwich with fresh mozzarella, tomato, and basil',
        prepTime: 8,
        cookTime: 0,
        yield: 1,
        yieldUnit: 'sandwich',
        costPerUnit: '2.5000',
        sellingPrice: '7.99',
        instructions: [
          'Slice ciabatta bread',
          'Layer fresh mozzarella slices',
          'Add thick tomato slices',
          'Top with fresh basil leaves',
          'Drizzle with balsamic glaze and olive oil',
          'Season with salt and pepper',
        ],
        nutritionalInfo: {
          calories: 420,
          protein: 18,
          carbs: 38,
          fat: 22,
          sodium: 680,
        },
        allergens: ['gluten', 'dairy'],
        tags: ['vegetarian', 'italian', 'fresh'],
        isActive: true,
      },
      {
        name: 'Veggie Wrap',
        category: 'sandwich',
        description: 'Healthy wrap filled with fresh vegetables and hummus',
        prepTime: 10,
        cookTime: 0,
        yield: 1,
        yieldUnit: 'wrap',
        costPerUnit: '2.2000',
        sellingPrice: '7.49',
        instructions: [
          'Spread hummus on large tortilla',
          'Layer spinach, cucumber, bell peppers, and carrots',
          'Add avocado slices',
          'Sprinkle with feta cheese',
          'Roll tightly and cut in half',
        ],
        nutritionalInfo: {
          calories: 380,
          protein: 12,
          carbs: 48,
          fat: 16,
          sodium: 540,
        },
        allergens: ['gluten', 'dairy'],
        tags: ['vegetarian', 'healthy', 'wrap'],
        isActive: true,
      },
      {
        name: 'Chicken Pesto Panini',
        category: 'sandwich',
        description: 'Grilled panini with chicken, pesto, and melted cheese',
        prepTime: 12,
        cookTime: 5,
        yield: 1,
        yieldUnit: 'sandwich',
        costPerUnit: '3.2000',
        sellingPrice: '9.99',
        instructions: [
          'Slice ciabatta bread',
          'Spread pesto on both sides',
          'Layer grilled chicken breast',
          'Add provolone cheese and sun-dried tomatoes',
          'Grill in panini press for 5 minutes',
        ],
        nutritionalInfo: {
          calories: 520,
          protein: 38,
          carbs: 42,
          fat: 22,
          sodium: 890,
        },
        allergens: ['gluten', 'dairy', 'nuts'],
        tags: ['grilled', 'chicken', 'italian'],
        isActive: true,
      },
      {
        name: 'Ham Cheddar Croissant',
        category: 'sandwich',
        description: 'Flaky croissant filled with ham and melted cheddar',
        prepTime: 8,
        cookTime: 3,
        yield: 1,
        yieldUnit: 'sandwich',
        costPerUnit: '2.6000',
        sellingPrice: '7.99',
        instructions: [
          'Slice croissant horizontally',
          'Layer sliced ham',
          'Add cheddar cheese slices',
          'Toast in oven until cheese melts',
          'Add honey mustard if desired',
        ],
        nutritionalInfo: {
          calories: 480,
          protein: 24,
          carbs: 36,
          fat: 26,
          sodium: 920,
        },
        allergens: ['gluten', 'dairy', 'eggs'],
        tags: ['croissant', 'ham', 'breakfast'],
        isActive: true,
      },

      // ========== SEASONAL/OTHER ==========
      {
        name: 'Pumpkin Spice Muffin',
        category: 'pastry',
        description: 'Moist pumpkin muffin with warm autumn spices',
        prepTime: 15,
        cookTime: 20,
        yield: 12,
        yieldUnit: 'muffins',
        costPerUnit: '0.6500',
        sellingPrice: '3.25',
        instructions: [
          'Mix flour, baking soda, spices, and salt',
          'Whisk pumpkin puree, eggs, oil, and sugar',
          'Combine wet and dry ingredients',
          'Fill muffin cups 2/3 full',
          'Bake at 180°C for 20 minutes',
          'Cool before serving',
        ],
        nutritionalInfo: {
          calories: 210,
          protein: 3,
          carbs: 32,
          fat: 8,
          sugar: 18,
        },
        allergens: ['gluten', 'eggs'],
        tags: ['seasonal', 'pumpkin', 'fall'],
        isActive: true,
      },
  ];

  // Filter out recipes that already exist
  const newRecipes = recipesToSeed.filter(recipe => !existingRecipeNames.has(recipe.name));

  if (newRecipes.length === 0) {
    console.log('⚠️  All recipes already exist, skipping insertion');
    // Fetch all recipes to use for ingredients
    const recipeList = await db.select().from(recipes);
    console.log(`✅ Using ${recipeList.length} existing recipes`);
    return; // Skip the rest since no new recipes to add
  }

  console.log(`📝 Inserting ${newRecipes.length} new recipes (${recipesToSeed.length - newRecipes.length} already exist)`);

  // Insert only new recipes
  const recipeList = await db
    .insert(recipes)
    .values(newRecipes)
    .returning();

  console.log(`✅ Created ${recipeList.length} recipes`);

  // Create recipe ingredients
  const ingredientsData: Array<{
    recipeId: string;
    ingredientId: string | null;
    ingredientName: string;
    quantity: string;
    unit: string;
    cost: string;
    notes: string | null;
  }> = [];

  // Sourdough Bread ingredients
  if (recipeList[0]) {
    ingredientsData.push(
      {
        recipeId: recipeList[0].id,
        ingredientId: getInventoryId('Bread Flour'),
        ingredientName: 'Bread Flour',
        quantity: '500',
        unit: 'g',
        cost: '0.7250', // 0.5kg * 1.45
        notes: 'High protein for structure',
      },
      {
        recipeId: recipeList[0].id,
        ingredientId: getInventoryId('Water'),
        ingredientName: 'Water',
        quantity: '350',
        unit: 'ml',
        cost: '0.0035', // negligible
        notes: 'Filtered water',
      },
      {
        recipeId: recipeList[0].id,
        ingredientId: getInventoryId('Active Dry Yeast'),
        ingredientName: 'Sourdough Starter',
        quantity: '150',
        unit: 'g',
        cost: '0.3000',
        notes: 'Active sourdough starter',
      },
      {
        recipeId: recipeList[0].id,
        ingredientId: getInventoryId('Fine Sea Salt'),
        ingredientName: 'Fine Sea Salt',
        quantity: '12',
        unit: 'g',
        cost: '0.0360', // 0.012kg * 3.00
        notes: null,
      },
    );
  }

  // Baguette ingredients
  if (recipeList[1]) {
    ingredientsData.push(
      {
        recipeId: recipeList[1].id,
        ingredientId: getInventoryId('Bread Flour'),
        ingredientName: 'Bread Flour',
        quantity: '600',
        unit: 'g',
        cost: '0.8700',
        notes: null,
      },
      {
        recipeId: recipeList[1].id,
        ingredientId: getInventoryId('Water'),
        ingredientName: 'Water',
        quantity: '400',
        unit: 'ml',
        cost: '0.0040',
        notes: null,
      },
      {
        recipeId: recipeList[1].id,
        ingredientId: getInventoryId('Active Dry Yeast'),
        ingredientName: 'Active Dry Yeast',
        quantity: '8',
        unit: 'g',
        cost: '0.1920',
        notes: null,
      },
      {
        recipeId: recipeList[1].id,
        ingredientId: getInventoryId('Fine Sea Salt'),
        ingredientName: 'Fine Sea Salt',
        quantity: '14',
        unit: 'g',
        cost: '0.0420',
        notes: null,
      },
    );
  }

  // Chocolate Chip Cookies ingredients
  if (recipeList[4]) {
    ingredientsData.push(
      {
        recipeId: recipeList[4].id,
        ingredientId: getInventoryId('All-Purpose Flour'),
        ingredientName: 'All-Purpose Flour',
        quantity: '300',
        unit: 'g',
        cost: '0.3750',
        notes: null,
      },
      {
        recipeId: recipeList[4].id,
        ingredientId: getInventoryId('Unsalted Butter'),
        ingredientName: 'Unsalted Butter',
        quantity: '200',
        unit: 'g',
        cost: '1.8000',
        notes: 'Room temperature',
      },
      {
        recipeId: recipeList[4].id,
        ingredientId: getInventoryId('Granulated Sugar'),
        ingredientName: 'Granulated Sugar',
        quantity: '150',
        unit: 'g',
        cost: '0.2250',
        notes: null,
      },
      {
        recipeId: recipeList[4].id,
        ingredientId: getInventoryId('Brown Sugar'),
        ingredientName: 'Brown Sugar',
        quantity: '150',
        unit: 'g',
        cost: '0.2550',
        notes: 'Packed',
      },
      {
        recipeId: recipeList[4].id,
        ingredientId: getInventoryId('Large Eggs'),
        ingredientName: 'Large Eggs',
        quantity: '2',
        unit: 'unit',
        cost: '1.0000',
        notes: null,
      },
      {
        recipeId: recipeList[4].id,
        ingredientId: getInventoryId('Vanilla Extract'),
        ingredientName: 'Vanilla Extract',
        quantity: '5',
        unit: 'ml',
        cost: '0.7500',
        notes: 'Pure vanilla',
      },
      {
        recipeId: recipeList[4].id,
        ingredientId: getInventoryId('Dark Chocolate Chips'),
        ingredientName: 'Dark Chocolate Chips',
        quantity: '300',
        unit: 'g',
        cost: '2.5500',
        notes: '60% cocoa',
      },
    );
  }

  // Vanilla Birthday Cake ingredients
  if (recipeList[5]) {
    ingredientsData.push(
      {
        recipeId: recipeList[5].id,
        ingredientId: getInventoryId('All-Purpose Flour'),
        ingredientName: 'All-Purpose Flour',
        quantity: '450',
        unit: 'g',
        cost: '0.5625',
        notes: 'Sifted',
      },
      {
        recipeId: recipeList[5].id,
        ingredientId: getInventoryId('Unsalted Butter'),
        ingredientName: 'Unsalted Butter',
        quantity: '250',
        unit: 'g',
        cost: '2.2500',
        notes: 'Room temperature',
      },
      {
        recipeId: recipeList[5].id,
        ingredientId: getInventoryId('Granulated Sugar'),
        ingredientName: 'Granulated Sugar',
        quantity: '350',
        unit: 'g',
        cost: '0.5250',
        notes: null,
      },
      {
        recipeId: recipeList[5].id,
        ingredientId: getInventoryId('Large Eggs'),
        ingredientName: 'Large Eggs',
        quantity: '4',
        unit: 'unit',
        cost: '2.0000',
        notes: 'Room temperature',
      },
      {
        recipeId: recipeList[5].id,
        ingredientId: getInventoryId('Vanilla Extract'),
        ingredientName: 'Vanilla Extract',
        quantity: '15',
        unit: 'ml',
        cost: '2.2500',
        notes: 'Pure vanilla',
      },
      {
        recipeId: recipeList[5].id,
        ingredientId: getInventoryId('Whole Milk'),
        ingredientName: 'Whole Milk',
        quantity: '240',
        unit: 'ml',
        cost: '0.7200',
        notes: 'Room temperature',
      },
      {
        recipeId: recipeList[5].id,
        ingredientId: getInventoryId('Baking Powder'),
        ingredientName: 'Baking Powder',
        quantity: '15',
        unit: 'g',
        cost: '0.1200',
        notes: null,
      },
      {
        recipeId: recipeList[5].id,
        ingredientId: getInventoryId('Fine Sea Salt'),
        ingredientName: 'Fine Sea Salt',
        quantity: '5',
        unit: 'g',
        cost: '0.0150',
        notes: null,
      },
      {
        recipeId: recipeList[5].id,
        ingredientId: getInventoryId('Powdered Sugar'),
        ingredientName: 'Powdered Sugar',
        quantity: '500',
        unit: 'g',
        cost: '1.5000',
        notes: 'For buttercream frosting',
      },
      {
        recipeId: recipeList[5].id,
        ingredientId: null,
        ingredientName: 'Rainbow Sprinkles',
        quantity: '50',
        unit: 'g',
        cost: '0.8500',
        notes: 'For decoration',
      },
    );
  }

  // Filter out any null ingredient IDs and insert
  const validIngredients = ingredientsData.filter(
    (ing): ing is typeof ing & { ingredientId: string } => ing.ingredientId !== null
  );

  if (validIngredients.length > 0) {
    await db.insert(recipeIngredients).values(validIngredients);
    console.log(`✅ Created ${validIngredients.length} recipe ingredients`);
  }

  console.log('🌱 Recipes seeding complete!');
}
