openapi: 3.0.0
info:
  title: BakeWind Customer API
  version: 1.0.0
  description: API endpoints for customer-facing operations

paths:
  /api/auth/register:
    post:
      summary: Register new customer account
      tags: [Authentication]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [email, password, firstName, lastName, phone]
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
                  minLength: 8
                firstName:
                  type: string
                lastName:
                  type: string
                phone:
                  type: string
      responses:
        201:
          description: Account created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthResponse'
        400:
          $ref: '#/components/responses/ValidationError'
        409:
          description: Email already exists

  /api/auth/login:
    post:
      summary: Customer login
      tags: [Authentication]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [email, password]
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
      responses:
        200:
          description: Login successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthResponse'
        401:
          description: Invalid credentials

  /api/auth/logout:
    post:
      summary: Customer logout
      tags: [Authentication]
      security:
        - bearerAuth: []
      responses:
        200:
          description: Logout successful

  /api/auth/refresh:
    post:
      summary: Refresh access token
      tags: [Authentication]
      responses:
        200:
          description: Token refreshed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthResponse'

  /api/locations:
    get:
      summary: Get all bakery locations
      tags: [Locations]
      parameters:
        - name: active
          in: query
          schema:
            type: boolean
          description: Filter by active status
      responses:
        200:
          description: List of locations
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/BakeryLocation'

  /api/locations/{locationId}:
    get:
      summary: Get location details
      tags: [Locations]
      parameters:
        - $ref: '#/components/parameters/locationId'
      responses:
        200:
          description: Location details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BakeryLocation'
        404:
          description: Location not found

  /api/products:
    get:
      summary: Get products catalog
      tags: [Products]
      parameters:
        - name: locationId
          in: query
          required: true
          schema:
            type: string
            format: uuid
        - name: category
          in: query
          schema:
            type: string
        - name: available
          in: query
          schema:
            type: boolean
        - name: page
          in: query
          schema:
            type: integer
            default: 1
        - name: limit
          in: query
          schema:
            type: integer
            default: 20
      responses:
        200:
          description: Products list
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Product'
                  pagination:
                    $ref: '#/components/schemas/Pagination'

  /api/products/{productId}:
    get:
      summary: Get product details
      tags: [Products]
      parameters:
        - $ref: '#/components/parameters/productId'
        - name: locationId
          in: query
          required: true
          schema:
            type: string
            format: uuid
      responses:
        200:
          description: Product details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        404:
          description: Product not found

  /api/cart:
    get:
      summary: Get current cart
      tags: [Cart]
      security:
        - bearerAuth: []
        - sessionId: []
      responses:
        200:
          description: Cart contents
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cart'

    post:
      summary: Add item to cart
      tags: [Cart]
      security:
        - bearerAuth: []
        - sessionId: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [productId, quantity, locationId]
              properties:
                productId:
                  type: string
                  format: uuid
                quantity:
                  type: integer
                  minimum: 1
                locationId:
                  type: string
                  format: uuid
      responses:
        200:
          description: Item added
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cart'
        400:
          $ref: '#/components/responses/ValidationError'

  /api/cart/items/{itemId}:
    patch:
      summary: Update cart item quantity
      tags: [Cart]
      security:
        - bearerAuth: []
        - sessionId: []
      parameters:
        - name: itemId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [quantity]
              properties:
                quantity:
                  type: integer
                  minimum: 0
      responses:
        200:
          description: Item updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cart'

    delete:
      summary: Remove item from cart
      tags: [Cart]
      security:
        - bearerAuth: []
        - sessionId: []
      parameters:
        - name: itemId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        200:
          description: Item removed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cart'

  /api/checkout/session:
    post:
      summary: Create checkout session
      tags: [Checkout]
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [orderType]
              properties:
                orderType:
                  type: string
                  enum: [pickup, delivery]
                pickupTime:
                  type: string
                  format: date-time
                deliveryAddress:
                  $ref: '#/components/schemas/Address'
                notes:
                  type: string
      responses:
        200:
          description: Checkout session created
          content:
            application/json:
              schema:
                type: object
                properties:
                  sessionId:
                    type: string
                  paymentIntentId:
                    type: string
                  clientSecret:
                    type: string
                  amount:
                    type: number
        400:
          $ref: '#/components/responses/ValidationError'

  /api/checkout/confirm:
    post:
      summary: Confirm payment and create order
      tags: [Checkout]
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [paymentIntentId]
              properties:
                paymentIntentId:
                  type: string
      responses:
        201:
          description: Order created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
        400:
          $ref: '#/components/responses/ValidationError'

  /api/orders:
    get:
      summary: Get customer orders
      tags: [Orders]
      security:
        - bearerAuth: []
      parameters:
        - name: status
          in: query
          schema:
            type: string
            enum: [pending, confirmed, preparing, ready, completed, cancelled]
        - name: page
          in: query
          schema:
            type: integer
            default: 1
        - name: limit
          in: query
          schema:
            type: integer
            default: 20
      responses:
        200:
          description: Orders list
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Order'
                  pagination:
                    $ref: '#/components/schemas/Pagination'

  /api/orders/{orderId}:
    get:
      summary: Get order details
      tags: [Orders]
      security:
        - bearerAuth: []
      parameters:
        - $ref: '#/components/parameters/orderId'
      responses:
        200:
          description: Order details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
        404:
          description: Order not found

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
    sessionId:
      type: apiKey
      in: cookie
      name: session_id

  parameters:
    locationId:
      name: locationId
      in: path
      required: true
      schema:
        type: string
        format: uuid
    productId:
      name: productId
      in: path
      required: true
      schema:
        type: string
        format: uuid
    orderId:
      name: orderId
      in: path
      required: true
      schema:
        type: string
        format: uuid

  responses:
    ValidationError:
      description: Validation error
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
              errors:
                type: array
                items:
                  type: object
                  properties:
                    field:
                      type: string
                    message:
                      type: string

  schemas:
    AuthResponse:
      type: object
      properties:
        accessToken:
          type: string
        user:
          $ref: '#/components/schemas/Customer'

    Customer:
      type: object
      properties:
        id:
          type: string
          format: uuid
        email:
          type: string
          format: email
        firstName:
          type: string
        lastName:
          type: string
        phone:
          type: string
        emailVerified:
          type: boolean
        createdAt:
          type: string
          format: date-time

    BakeryLocation:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        address:
          type: string
        city:
          type: string
        state:
          type: string
        postalCode:
          type: string
        country:
          type: string
        phone:
          type: string
        email:
          type: string
        timezone:
          type: string
        isActive:
          type: boolean
        openingHours:
          type: object
        coordinates:
          type: object
          properties:
            lat:
              type: number
            lng:
              type: number

    Product:
      type: object
      properties:
        id:
          type: string
          format: uuid
        sku:
          type: string
        name:
          type: string
        description:
          type: string
        category:
          type: string
        price:
          type: number
        currency:
          type: string
        images:
          type: array
          items:
            type: string
        allergens:
          type: array
          items:
            type: string
        ingredients:
          type: array
          items:
            type: string
        isAvailable:
          type: boolean
        preparationTime:
          type: integer
        servingSize:
          type: string
        nutritionInfo:
          type: object

    Cart:
      type: object
      properties:
        id:
          type: string
          format: uuid
        locationId:
          type: string
          format: uuid
        items:
          type: array
          items:
            $ref: '#/components/schemas/CartItem'
        subtotal:
          type: number
        tax:
          type: number
        total:
          type: number
        createdAt:
          type: string
          format: date-time
        expiresAt:
          type: string
          format: date-time

    CartItem:
      type: object
      properties:
        id:
          type: string
          format: uuid
        product:
          $ref: '#/components/schemas/Product'
        quantity:
          type: integer
        totalPrice:
          type: number
        addedAt:
          type: string
          format: date-time

    Order:
      type: object
      properties:
        id:
          type: string
          format: uuid
        orderNumber:
          type: string
        customer:
          $ref: '#/components/schemas/Customer'
        location:
          $ref: '#/components/schemas/BakeryLocation'
        status:
          type: string
          enum: [pending, confirmed, preparing, ready, completed, cancelled]
        items:
          type: array
          items:
            $ref: '#/components/schemas/OrderItem'
        subtotal:
          type: number
        tax:
          type: number
        deliveryFee:
          type: number
        total:
          type: number
        paymentStatus:
          type: string
          enum: [pending, completed, failed, refunded]
        orderType:
          type: string
          enum: [pickup, delivery]
        pickupTime:
          type: string
          format: date-time
        deliveryAddress:
          $ref: '#/components/schemas/Address'
        notes:
          type: string
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time

    OrderItem:
      type: object
      properties:
        id:
          type: string
          format: uuid
        product:
          $ref: '#/components/schemas/Product'
        quantity:
          type: integer
        unitPrice:
          type: number
        totalPrice:
          type: number
        customizations:
          type: object
        specialInstructions:
          type: string

    Address:
      type: object
      properties:
        id:
          type: string
          format: uuid
        label:
          type: string
        street1:
          type: string
        street2:
          type: string
        city:
          type: string
        state:
          type: string
        postalCode:
          type: string
        country:
          type: string
        isDefault:
          type: boolean

    Pagination:
      type: object
      properties:
        page:
          type: integer
        limit:
          type: integer
        total:
          type: integer
        totalPages:
          type: integer